### ISSUE TITLE
unison-fsmonitor consumes infinite memory when the main unison process crashes

### ISSUE THREAD

**Issue by JBYoshi** [bcpierce00/unison#1053]
I'm using Unison in command-line mode on a Mac with fsmonitor mode enabled. When my laptop goes to sleep, it disconnects the SSH connections. This causes the main Unison process to exit, but the unison-fsmonitor process continues to run. It rapidly starts eating as much system memory as it can until macOS pops up an error that the system ran out of memory.

I can reproduce this by starting Unison with the FS monitor enabled and then running `killall unison`. Alternatively, running `sleep 1 | unison-fsmonitor` also causes the memory usage to blow up in what I think is similar circumstances; the latter spams a log message saying "ERROR Unrecognized%20cmd%3A%20".

I installed Unison using Homebrew. `unison -version` returns `unison version 2.53.5 (ocaml 5.1.0)`.

**Comment by gdt** [comment]
On NetBSD 10, just starting unison-fsmonitor leads to a stable situation of
```
USER       PID %CPU %MEM      VSZ    RSS TTY    STAT STARTED      TIME COMMAND
abc      13971  0.0  0.0    34792   2852 pts/7  Il+   1:57PM   0:00.00 ./unison-fsmonitor 
```
which is piggy, but not growing.   When I pipe `sleep 1` into it, it runs for a second and exits, so I don't follow.

Repro attempts in other environments would be helpful.  Also, you didn't specify your OS version.   It would help to characterize the growth in terms of KB/s or MB/s.

If you want to debug this, I would look for whatever is reading or writing.  It smells like a read or write call getting an error return and this being misinterpreted, perhaps because actual nonblocking status doesn't match what the code is expecting -- but I am way way out on a limb there.

**Comment by tleedjarv** [comment]
This repo does not have code for a Mac `unison-fsmonitor` so you must have a third party implementation installed.

**Comment by JBYoshi** [comment]
> This repo does not have code for a Mac `unison-fsmonitor` so you must have a third party implementation installed.

Now that I look at it... yeah, that's the case. The version I'm using already has that issue reported. Closing.

https://github.com/autozimu/unison-fsmonitor/issues/27
