### ISSUE TITLE
Sync two computers both ways at same time

### ISSUE THREAD

**Issue by vsespb** [bcpierce00/unison#132]
If I run unison on PC1 to sync between folder A on PC1 folder B on PC2. And at the same time I run unison on P2 to sync same folders, but from PC2. And in both cases I use "-repeat" (maybe "-repeat watch"). Will it work? Will it work well? Is there a risk to damage data?

**Comment by bcpierce00** [comment]
Why would you want to do that?  Just one copy of Unison will sync data in both directions.

**Comment by Massimo-B** [comment]
This is not completely pointless. I'm using 2 computers and running -repeat watch on both. I'm the only user. Leaving computer A I need to make sure I stopped the -repeat watch, but what if not?
From what I see the watcher synchronizes all changed local files immediately. But remote files it doesn't. Remote in my case means a WebDAV webserver mounted locally via davfs2. So the watcher would need to pull files to see if something has changed I guess. Does it?

If not the -repeat watch left running shouldn't change anything but also does not get changes from remote.

For being save I usually run an interactive sync first and then switch to -repeat watch which is always non-interactive. But this means some manual work for having 3 unison setups.

There are other solutions like csync, keeping whole $HOME directories in sync. But as those solutions are always non-interactive I always preferred unison since many years (thanks for continuing the development after being quiet for a while).
I also have other solutions syncing to a central WebDAV from mobile devices using Foldersync on Android. So it is never guaranteed that only one instance is syncing at a time.

**Comment by vsespb** [comment]
> From what I see the watcher synchronizes all changed local files immediately. But remote files it doesn't. 

That's exactly why I was going to sync from both machines (but I was not sure). I suspect only client machine can do `watch` and do instant synchronization. Still not sure!

If there is way to do instant sync from both machines, and if I have only two in total, then there is no point in using SyncThing, because Unison will work, otherwise SyncThing has an advantage.

**Comment by bcpierce00** [comment]
One instance of Unison should run watchers on both client and server.

**Comment by vsespb** [comment]
ok thx!

**Comment by Massimo-B** [comment]
> One instance of Unison should run watchers on both client and server.

So with this hint you mean, a watcher can only push changes? Please make that a bit more clear, what the server and what the client is. I don't have a unison server, only clients.
I use a central Webdav for centralized synchronization.

I have 3 clients with unison and 4 clients with Android Foldersync synchronizing to that central point. Unison uses the mountpoint of davfs2. Unison has 3 different setups for ~/Documents, ~/Pictures and $HOME and one shared with common settings included by the others:
```
 .unison/DAV_Common.prf
 .unison/DAV_Documents.prf
 .unison/DAV_Home.prf
 .unison/DAV_Pictures.prf
```

I experimented a lot with davfs2 and unison and would like to share the results in this context:
https://forums.gentoo.org/viewtopic-t-695019.html
https://savannah.nongnu.org/support/?108539
https://savannah.nongnu.org/bugs/?27191

------------------------
```ini
$ cat .unison/DAV_Documents.prf 
root = /home/mb
root = /mnt/webdav

mountpoint = Documents
path = Documents

ignore = Name .*.swp
ignore = Name .~lock.*
ignore = Name *.dtapart

include DAV_Common
```
------------------------
```ini
$ cat .unison/DAV_Pictures.prf 
root = /home/mb
root = /mnt/webdav

mountpoint = Pictures
path = Pictures

ignore = Name *digikam*
ignore = Name *.MP4

include DAV_Common
```
------------------------
```ini
$ cat .unison/DAV_Home.prf 
root = /home/mb
root = /mnt/webdav

mountpoint = .jameica
path = .jameica

ignore = Path .jameica/*.gz
ignore = Path .jameica/*.zip
ignore = Path .jameica/jameica.lock
ignore = Name {*.tmp,*.log}

include DAV_Common
```
------------------------
```ini
$ cat .unison/DAV_Common.prf 
log = false
perms = 0
dontchmod = true
links = false
fastcheck = no
confirmbigdel = true
ignoreinodenumbers = true
maxthreads = 8
clientHostName = gentoo-mb
```
------------------------
```ini
$ cat .davfs2/davfs2.conf 
cache_size      52000
table_size      81920
#file_refresh    0
#dir_refresh     0
delay_upload    15
gui_optimize    1
secrets         ~/.davfs2/secret
use_compression 1
#debug           most
```

**Comment by bcpierce00** [comment]
Sorry my comment was not clear.  

By “client” and “server” I just meant the copies of the unison binary running on the two machines being synchronized.  “Client” is the copy that invokes the synchronization (and displays the UI); “server” is the one on the remote host.  

By “watcher” I meant a sub-process that is invoked by unison to detect changes to the local filesystem and report them back to the main unison process.

So what I wanted to convey was that the client and the server unison process each run their own local watcher to detect changes on their local filesystem.  (And therefore there is no need to run two copies of unison in order to continuously detect changes on both sides.)
