### ISSUE TITLE
Check for used compiler version before sync

### ISSUE THREAD

**Issue by buhtz** [bcpierce00/unison#15]
When syncing unison check the version string of the other side and give an error if there is a difference. This only works for the unison version itself.

There should be a check vor the version of the used ocaml compiler/lib, too.

We know that there are often reported problems about some errors (e.g. "bad bigarray kind"), when the same unison version is build with different Ocaml versions. e.g. This happen when using Unision from Ubuntu Xenial with and Unision from Debian unstable.

**Comment by alainm** [comment]
That use of Unison across versions of OSes is very fundamental  to the 
essence of Unison.

This compiler version thing will become a major issue shortly. I hope that 
you guys find a fix for it !

Ah, btw, thanks for it all :)


-----
Alain Mouette



A 22 de maio de 2016 04:34:08 buhtz <notifications@github.com> escreveu:

**Comment by bcpierce00** [comment]
OK, I've made various changes in response to this.  Two good suggestions were improving the error message at the failure point to suggest that a compiler version mismatch might be the issue and making the 'Contacting server...' message that's printed at startup include the compiler version; I've done these in the developer version and 2.48.4.  In the newest version, I've also made the connection header (which is sent from the server back to the client so that the client can confirm that versions match) include an indication of whether the OCaml version is >=4.02.2.  

I haven't actually been able to replicate the failure myself, though.  It would be great if someone for whom things are failing could download the new 2.48.4, compile it under two different OCaml compilers, and check that the failure is caught and reported more cleanly now.

**Comment by bcpierce00** [comment]
Closing this issue for now.

**Comment by jegi** [comment]
I've fallen into this hole, with Unison 2.40.69 on OS X 10.6.8. I can't use any of the newer binaries on this old OS (and it's an ancient machine, so I can't easily change the OS either). Would it be possible to make available a Mac binary of 2.40.* compiled with ocaml 4.02.*?

**Comment by jegi** [comment]
Great - ta, I'll ask there.
