### ISSUE TITLE
add improved sorting in the main window (gtk)

### ISSUE THREAD

**Issue by buhtz** [bcpierce00/unison#17]
I am not sure if this works in other gui-versions so I write about gtk here.

It should be possible to sort for all columns. I miss to sort for "Actions".

And beside of it there should be a way to sort by clicking on the head of each column. This is a usual behaviour in the most gui-frameworks.

**Comment by bcpierce00** [comment]
Agreed -- it would be nice to improve the GTK UI in this way.  Happy to consider a patch if someone wants to do it.

**Comment by buhtz** [comment]
Nice to here that Unison's development is going on.
But sorry, I'm not able to test because I'm not using it anymore.

btw: Think about "wontfix" label. It is not polite to users and contributors no matter how you really meant it.
"fix" implicates a bug. So you see a bug but don't agree to fix it (no matter how and when and which what ressources!)? I assume you doesn't mean it that way.

Using a label that better describes why you won't further investigate or work on that issue might be more informative and helpful to your users.

**Comment by gdt** [comment]
wontfix means exactly: "maintainers choose not to work on this, but PR would still be considered."  This can be seen as a tooltip when hovering over it.   It's the nature of labels that they are terse, and that I'm trying not to have too many because it's clutter and harder to set them.

I don't know what you mean about "no matter .. resources".  There are only two people regularly contributing to maintenance, and I'd say about 0.3 FTE.    If you mean some future theoretical world where there are 10 FTEs of paid staff to work on issues, that's so fantastical that I do ignore that possibility.

**Comment by gdt** [comment]
Moved to https://github.com/bcpierce00/unison/wiki/Feature-Requests
