### ISSUE TITLE
How to watch for changes on both replicas?

### ISSUE THREAD

**Issue by lifepillar** [bcpierce00/unison#182]
This is partly related to https://github.com/bcpierce00/unison/issues/132.

I have set up Unison to sync a folder on my laptop to my remote desktop via SSH. I am using the command-line tool, not the GUI. Both replicas run under macOS. My laptop contains Unison and a profile, while the remote desktop just contains Unison executable (no profile there). Currently, I am using a launchd daemon in my laptop to watch for changes and launch Unison on demand. This allows me to watch for changes locally (in the laptop).

My goal is to have synchronization fire as soon as a change is detected in *any* of the replicas. Bonus point: synchronize only the subdirectory that has changed instead of the whole root.

So, first question: is `-watch` implemented in macOS?

Second, in https://github.com/bcpierce00/unison/issues/132, you wrote:

>the client and the server unison process each run their own local watcher to detect changes on their local filesystem.  (And therefore there is no need to run two copies of unison in order to continuously detect changes on both sides.)

I don't understand this. Is the watcher process that runs Unison on demand? With reference to my configuration, when a change occurs in the desktop, should the watcher local to the desktop notify the unison executable in my laptop?

**Comment by lihume** [comment]
If unison has this feature build in, I don't know either, I guess not. For me the solution to this problem is using an **incron daemon** (see [incron](https://github.com/ar-/incron)) watching for changes in my file system and than triggering unison via a bash script.

The incron daemon allows you to define paths with a mask of events that will trigger a command. E.g.:

`/var/www/uploads IN_CREATE,IN_CLOSE_WRITE,IN_MOVED_TO /etc/cloud/unisonScript.sh $@ $# $%`

This way it is easy to watch for specific changes and run unison syncs on demand. 

I suggest you to use it with care, as monitoring every little change can also lead to an avalanche of syncs which crashed my server. Of course it depends very much on your application.

The only downside seems it is not available for macOS, see [this thread](https://superuser.com/questions/182408/how-to-automatically-launch-a-shell-script-when-content-of-a-given-directory-is), but there might be other ways to do so.

I hope this can help.

**Comment by gdt** [comment]
Please use the malinglist for support questions.
