### ISSUE TITLE
Non-existent folder causes other folder to be deleted

### ISSUE THREAD

**Issue by maxiedaniels** [bcpierce00/unison#206]
I'm trying to get Unison to sync between two folders, but on one side, if I don't have the existing folder, it tries to delete the other side (the folder with everything in it). I think it's due to me using '-prefer newer', but I want to keep that, as I'd like the newest file/folder changes *within* the root folders to be propagated. Is this intended functionality?? Is there any way around this?

*edit* Sorry, I realize adding -ignorearchives fixed the direct issue, which I guess was that I initially tried syncing folderA (full of files) with folderB (existing but empty folder). However, in that case, I'd still like to find a way to assume propagation from folderA to folderB, if going the opposite way would result in a massive deletion... is that possible?

**Comment by gdt** [comment]
Related to #262

**Comment by glondu** [comment]
The initial report is too imprecise. It should be rephrased in terms of how things evolved on both sides since the previous run of unison (this is how unison works).

Could you explain the story with the folder not existing on one side? If it existed on both sides and something removed it on one side, then it's correct that Unison propagates the removal to the other side. If, on the other hand, it didn't exist on either side and you created it only on the other side, then Unison should propagate the "creation" to the first side.

I don't think `-prefer newer` (which acts in case of conflicts) is relevant here.

**Comment by tleedjarv** [comment]
As @glondu explained, it seem very likely that Unison has behaved correctly in response to the steps you had taken.

> it tries to delete

Could you clarify what do you mean by "_tries_ to delete"? Do you mean that `confirmbigdel` stops the actual deletion or that you were running in interactive mode and stopped the process after the updates had been reconciled but before synchronization?

**Comment by gdt** [comment]
Please bring this up on the ilst if still relevant; so far this seems not to be a bug.
