### ISSUE TITLE
stack overflow in GUI if number of changes is huge

### ISSUE THREAD

**Issue by pdo-smith** [bcpierce00/unison#207]
From Ubuntu Linux 18.04 I get the following error while running unison-gtk 2.48.4-1ubuntu1, taken from the Ubuntu repository:

Fatal error

Uncaught exception Stack overflow
Raised by primitive operation at file "array.ml", line 139, characters 14-41
Called from file "/build/unison-Y9EcQW/unison-2.48.4/uigtk2.ml", line 3401, characters 12-55
Called from file "/build/unison-Y9EcQW/unison-2.48.4/uigtk2.ml", line 156, characters 18-22
Called from file "/build/unison-Y9EcQW/unison-2.48.4/uigtk2.ml", line 3919, characters 4-37
Called from file "/build/unison-Y9EcQW/unison-2.48.4/uigtk2.ml", line 4276, characters 4-16

**Comment by pdo-smith** [comment]
I get the same error with the newest version of Unison, 2.51.2, built on my machine. I have been using Unison for years without any problems, until now.

Fatal error

Uncaught exception Stack overflow
Raised by primitive operation at file "array.ml", line 139, characters 14-41
Called from file "/home/peter/Downloads/unison-2.51.2/src/uigtk2.ml", line 3401, characters 12-55
Called from file "/home/peter/Downloads/unison-2.51.2/src/uigtk2.ml", line 156, characters 18-22
Called from file "/home/peter/Downloads/unison-2.51.2/src/uigtk2.ml", line 3919, characters 4-37
Called from file "/home/peter/Downloads/unison-2.51.2/src/uigtk2.ml", line 4279, characters 4-16

**Comment by pdo-smith** [comment]
Thanks for your reply.
The history is this:
1) I (unwisely)executed the following command on my file system: _chmod -R 771 *_
2) I ran Unison and got the error reported above.
3) I downloaded and compiled the latest version of Unison
4) I ran Unison once more and experienced the same error.
5) I executed the following command on my file system: _chmod -R u=rwX,g=rwX,o=r *_
6) I ran Unison again and it worked perfectly this time!

I have since run it several times on the same file system and it continues to work perfectly. I am of course very happy about this but remain puzzled that the original chmod should have provoked the error. The file system contains 741000 files and is not very deeply nested.

Unison is my production back up tool and I have routinely used it on this file system, with complete success, for years.

**Comment by bcpierce00** [comment]
Ah, so probably the failure was because the GUI code choked on trying to build a window 741k lines long!

   - B

**Comment by bcpierce00** [comment]
Apparently so!

       - Benjamin

**Comment by rudolphi** [comment]
I had the same problem after installation of Netbeans 9.0, which created a huge number of files (about 200k) by migrating some data. After manually rsyncing these files to the backup machine, unison syncing returned to working state. However, you should consider at least raising the limits a bit, or displaying something like "new branch X, contains 450 subfolders and 179450 files" - as otherwise many people may consider unison just "broken", without digging deeper for the actual cause.

Regards, Felix

**Comment by pdo-smith** [comment]
The limit is possibly set by the GTK widget, so probably not much can be done there. Unison needs to catch the exception and print a corresponding message. In this way it can fail gracefully.

**Comment by bcpierce00** [comment]
Happy to consider a PR if somebody wants to patch it.

**Comment by deragon** [comment]
I spend 30 minutes attempting to build or figure out how to build 'unison-gtk' to no vail.  Since this is a C base program, it is not easy to jump into the code and get started right a way (Java dev here and in my world, you download the source and it always fetches automagically the dependencies and builds every time; one starts coding 3 minutes after the download).  I do not have the luxury to continue digging (so many other projects).  I will use the workaround and run the unison cli tool to sync the first time.

**Comment by kiplingw** [comment]
@deragon, if you are on a Debian based system like Ubuntu, the process is very simple to build the package:

```
$ sudo apt build-dep unison-gtk
$ apt source unison-gtk
$ cd unison...
$ dpkg-buildpackage -uc -b
```

**Comment by tleedjarv** [comment]
I invite everyone to try out PR #386 to see if it fixes the problem you are experiencing.
