### ISSUE TITLE
Feature request: allow bandwidth used to be limited

### ISSUE THREAD

**Issue by PAGWatson** [bcpierce00/unison#258]
Hello, unison is a very useful tool, but one issue I've come across is that if a large directory needs to be copied for the first time, this can take a long time and saturate the bandwidth, slowing down other tasks that use the internet connection. I thought that an option to limit the bandwidth being used would allow users to keep enough upload bandwidth free so that other tasks are not slowed too much, in a similar way to the --bwlimit option for rsync. I couldn't see such an option at present.

**Comment by bcpierce00** [comment]
Did you try maxthreads?

**Comment by PAGWatson** [comment]
Thanks. I've tried using "-maxthreads 1" and it seems to still use the whole bandwidth - I can't test right now whether this slows down other processes like what I was trying to do yesterday, though (I'm on my work connection which is pretty fast anyway). Is the idea approximately that unison will by default have multiple threads, each allocated a share 1/N of the bandwidth where N is the total number of processes transferring data, so that setting maxthreads to M limits the total share used by unison to M/N? If so, is there a reason not to use "-maxthreads 1" all the time?

**Comment by bcpierce00** [comment]
Nothing quite so sophisticated.  The idea as I recall it is that each transfer is doing a certain amount of reasonably frequent handshaking, so in particular large file transfers over high-latency connections cannot saturate the connection.  Allowing multiple transfers in parallel helps with this (in the case where you actually want to saturate).  Sounds like your problem is your network is too fast!  :-)

Fixing things in this case might take a bit of work (I'm not sure, personally, how to tell how much of the network a given connection is using, especially not in a portable way), which is unlikely to happen without a volunteer.  But we'd be happy to consider a patch.

**Comment by PAGWatson** [comment]
OK I'll try it back on my home connection (which has a normal broadband speed, where I had the original issue).

**Comment by PAGWatson** [comment]
At home, it does seem to work better with "-maxthreads 1". I'll keep trying it out and see if any more issues arise.
