### ISSUE TITLE
2.51.2 failing to make/build on CloudLinux 7.6 

### ISSUE THREAD

**Issue by reagle** [bcpierce00/unison#271]
Just built ocaml, and now trying to build unison on webhost with the following architecture:

```
Operating System: CloudLinux 7.6 (Vladimir Lyakhov)
CPE OS Name: cpe:/o:cloudlinux:cloudlinux:7.6:GA:server
Kernel: Linux 3.10.0-962.3.2.lve1.5.25.10.el7.x86_64
Architecture: x86-64
```

The build fails:

```
[~/tmp/unison-2.51.2]# make UISTYLE=text
make -C src UISTYLE=text
make[1]: Entering directory `/home/goateene/tmp/unison-2.51.2/src'
UISTYLE = text
Building for Unix
NATIVE = true
THREADS = false
STATIC = false
OSTYPE =
OSARCH = Linux
ocamlopt: system.ml ---> system.cmx
ocamlopt -g -unsafe-string -I lwt -I ubase -I system -I fsmonitor -I fsmonitor/linux -I fsmonitor/windows -I system/generic -I lwt/generic -c /home/goateene/tmp/unison-2.51.2/src/system.ml
File "/home/goateene/tmp/unison-2.51.2/src/system.ml", line 1:
Error: The implementation /home/goateene/tmp/unison-2.51.2/src/system.ml
       does not match the interface system.cmi:
       Values do not match:
         val link : ?follow:bool -> string -> string -> unit
       is not included in
         val link : fspath -> fspath -> unit
       File "/home/goateene/tmp/unison-2.51.2/src/system/system_intf.ml", line 70, characters 0-35:
         Expected declaration
       File "/home/goateene/tmp/unison-2.51.2/src/system/system_generic.ml", line 50, characters 4-8:
         Actual declaration
make[1]: *** [system.cmx] Error 2
make[1]: Leaving directory `/home/goateene/tmp/unison-2.51.2/src'
make: *** [text] Error 2
```

**Comment by bcpierce00** [comment]
What OCaml version is this?  (ocaml -v)

**Comment by reagle** [comment]
```# ocaml --version
The OCaml toplevel, version 4.08.0```

(`-v` doesn't work.)

**Comment by bcpierce00** [comment]
(Sorry — should have said ‘ocamlc -v’.  But you found the information we needed.)

Looks like 4.08, which is very new, may not work yet with the unison sources.  4.07 should work.

    - B

**Comment by Hwwipp** [comment]
I encounter the same issue on Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-83-generic x86_64).
Trying to build unison 2.51.2 with ocaml 4.08 fails with the same error:
`Error: The implementation /home/hediwi/MyScripts/unison-make/unison-2.51.2/src/system.ml
       does not match the interface system.cmi:
       Values do not match:
         val link : ?follow:bool -> string -> string -> unit
       is not included in
         val link : fspath -> fspath -> unit
       File "/home/hediwi/MyScripts/unison-make/unison-2.51.2/src/system/system_intf.ml", line 70, characters 0-35:
         Expected declaration
       File "/home/hediwi/MyScripts/unison-make/unison-2.51.2/src/system/system_generic.ml", line 50, characters 4-8:
         Actual declaration`

The latest comment is no longer valid, because 2.51.2 builds with ocaml 4.08 on Arch and ocaml 4.06/4.07 on Ubuntu are no longer syncing, as documented in the unsison yahoo groups discussion [https://groups.yahoo.com/neo/groups/unison-users/conversations/topics/12462;_ylc=X3oDMTM1ZHBpM2VpBF9TAzk3MzU5NzE0BGdycElkAzQ3OTc2NwRncnBzcElkAzE3MDUwMDQ3MjYEbXNnSWQDMTI0ODIEc2VjA2Z0cgRzbGsDdnRwYwRzdGltZQMxNTY3OTg0ODUwBHRwY0lkAzEyNDYy](url).
Please fix this issue. Thanks

**Comment by Hwwipp** [comment]
I built unison successfully on ocaml 4.08 using [this ocaml 4.08 compatibility patch](https://git.archlinux.org/svntogit/packages.git/tree/trunk/4.08-compatibility.patch?h=packages/unison) from the arch linux package.
The issue could be closed.
