### ISSUE TITLE
Add support for syncing creation times

### ISSUE THREAD

**Issue by melyux** [bcpierce00/unison#285]
Will creation times be supported? Looks like Linux finally added API support for getting creation timestamps from files on filesystems that support it. Mac and Windows have already supported it for decades, so Linux is playing catch-up. Perhaps a potential PR if I can manage it would go over well?

Seems like there's some support for it:

* https://unix.stackexchange.com/questions/417446/can-unison-be-made-to-preserve-file-creation-dates
* https://superuser.com/questions/666653/retaining-creation-date-with-unison
* https://superuser.com/questions/1193272/unison-with-macos-and-times-set-to-true-times-true

**Comment by bcpierce00** [comment]
Yes, this is worth considering, if you or someone wants to take it on.  Some things to think about:

- Does the OCaml standard library support creation times reliably, or does it also need to be fixed?  
- This will change the wire format for Unison, so we'd want to roll this change out at the same time as any other compatibility-breaking changes people have in mind.  (At the moment, there aren't any planned that I know of.  So there's a question whether this feature is worth introducing a new major version for all by itself.)

**Comment by gdt** [comment]
A further question is if there is a standard for creation time, or if it's just the obvious extension from POSIX.   Also if rsync/etc. supports this, as setting creation time to other than the creation time seems a bit sketchy.

**Comment by gdt** [comment]
POSIX does not seem to specify creation time.   I'm going to hit close on this, because in unison we can't even get people to test code when the number one most wanted feature is implemented, and I don't want to head down the path of supporting things not required by POSIX unless it's widely implemented and a big deal.    If you want to figure out the interfaces, see if they are specified and/or widely portable, and discuss rationale on unison-hackers@, that's entirely welcome, but until there's an ok portability story it is speculative.
