### ISSUE TITLE
[linux-gtk] 'Delete' as Another Sync Option

### ISSUE THREAD

**Issue by kerner1000** [bcpierce00/unison#319]
Currently, you can choose to sync 'left' and 'right'.
I would like to have another option, that is to 'delete' the according file.

**Comment by gdt** [comment]
This doesn't quite make sense to me.   Are you saying that a file has been changed on both sides, and the UI is asking you which way to sync it?  And you really want to say "delete on both sides"?  That sounds out of scope for unison, which is a sync tool, not a general file manager.

If you want to keep this open, please give a specific example, and also explain if this is specific to the GUI or if the underlying behavior issue is the same in the text UI.

**Comment by kerner1000** [comment]
I frequently do (UI-)integration tests (of desktop-environments such as Gnome or KDE or system images) and use unison to generate a 'file-diff' of those systems under different configurations.
This way I can easily track changes that are done through an (UI-)interface and make them reproducible.
In order to fast-reset a configuration, I delete affected files. The fastest way to do so would just press a button in the unison UI.
I agree that this is a kind of specific use case. But I follow the same approach when syncing my home directory to a new machine.
Technically, I think the 'delete' option goes in line with the 'ignore' option, which would also serve my needs when synchronizing my home directory to a fresh machine. The problem with the ignore option is only that the ignore list gets large and cluttered with time.
I think this would affect any UI but could kept out of the unison 'core' module, if the 'delete file' function is implemented in the UI and not passed over to the model/ core.





 frequently run into the situation that I sync my files to a new machine
I admit that this request might be some kind of 

I frequently run into the situation that I sync my files to a new machine. I could save some time, if I could directly choose to delete files which I don't need anymore.

**Comment by gdt** [comment]
You still  haven't really clearly explained.   Under what circumstances would this option be offered?   Do you mean to prompt the user to delete even if neither replica has a change?  If one has been deleted and the other isn't (but it does that already).

Or do you mean to turn the unison sync ui into  a file manager that can do arbitrary file operations that are not related to approving sync operations or resolving conflicts?

Are you volunteering to write the code, and want confirmation it would in principle be merged, or are you asking others to write this for you?  (We don't have any norms about feature requests, but usually feature requests are things that would be of general interest.)

(My own view is that unison is far from having kept up with actual bugs, and that adding file manager features seems beyond what is reasonably feasible, separately from deciding that going beyond sync is reasonable.)

I have added "discuss" because I understand enough to know this is controversial.

**Comment by kerner1000** [comment]
I was imagining a button just like the ones for 'left', 'right', 'ignore', that will delete this file, no matter the sync state.
No changes besides this, just another 'sync option', as I would understand it.
I have zero experience with writing GTK or C code, so unfortunately I cannot volunteer to write the code.
I one offered on the mailing list to pay for the implementation to someone who is capable of doing so (I was referring to this issue in the mail to keep the discussion public). Interest for this offer was basically zero ;)
If there is no resources to implement this feature, that is fine, I can understand. We can mark the issue accordingly.

**Comment by glondu** [comment]
This feature does not seem complicated to do, but seems off-topic for Unison which is not, as @gdt said, a file manager.

**Comment by gdt** [comment]
Given two votes as off topic and no real interest on anyone's part in coding, I think this is below threshold to take up cognitive space in the tracker.  (Of course, anyone is welcome to modify their copy and use it, and if there's actual code, we can discuss again.)

**Comment by timur-g** [comment]
I am interested in this, need to delete one when having different names like same-file_old-version and  same-file_new-version.
