### ISSUE TITLE
Protocol error on roots with 1.2E9 files (integer overflow, but x86-64??)

### ISSUE THREAD

**Issue by jgupta** [bcpierce00/unison#340]
We are using the latest master branch on Linux CentOS 7. We are trying to sync 6TB of data. Every time we run Unison, we get the following error.

```
[pred] immutable '8/1571375835' = false
[pred] ignore '8/1571375835/execution' = false
[update] buildUpdateRec: 8/1571375835/execution
[update]   buildUpdate -> New directory
[pred] immutable '8/1571375835/execution' = false
[update] Setting archive for //HOSTNAME//var/www
$<>$<>$<>$<>$<>$<>$<>$<>$<>$<>$<>$Fatal error: Protocol error: corrupted message received;
if it happens to you in a repeatable way,
please post a report on the unison-users mailing list.

Fatal error: Protocol error: corrupted message received;
if it happens to you in a repeatable way,
please post a report on the unison-users mailing list.
[statsgen] Removing lock. Exit: ENO_SUCCESS(0)
```

**Comment by jgupta** [comment]
Splitting data into two (~3TB each) and running Unison on them one by one worked. It appears Unison has some limitations with the number of files it can handle.

**Comment by gdt** [comment]
Please explain what ocaml version, and if you are sure it's the same on both sides.

I realize it's a hard experiment, but if you can figure out if it's number of files vs amount of data vs ? that is probably useful, and if you can figure out the actual number.

**Comment by gdt** [comment]
Also, CPU type; I am unclear on ocaml types (sizeof int, basically) and if they vary by CPU arch - but I would expect not.

**Comment by skjardenCode** [comment]
I'm also interested in this problem - I am planning to sync two 16 TB disks with unison (debian). The file count is not very high, these are rather big files, so I hop I don't see this issue.

**Comment by tleedjarv** [comment]
This could definitely be an integer overflow on a 32-bit platform because OCaml int on 32-bit platforms is 30 bits, or 1073741823. However, at least one Unison code path relevant to this issue is already protected against integer overflow: https://github.com/bcpierce00/unison/blob/master/src/remote.ml#L678-L682

@skjardenCode, have you already made the sync attempt? Could you please report back the results here. I think it is safe to assume you are on a 64-bit system. Whether successful or not, could you also report the size of the largest file you attempted to sync?

**Comment by skjardenCode** [comment]
> @skjardenCode, have you already made the sync attempt? Could you please report back the results here. I think it is safe to assume you are on a 64-bit system. Whether successful or not, could you also report the size of the largest file you attempted to sync?

@tleedjarv I recently done the sync between two rather large HDDs. These are the specs:

- **HDD size**: 16 TB
- **Number of files**: ~ 170000
- **Size of largest file**: ~ 17.6 GB
- **System**: Linux Debian 10 (Buster), 64 Bit
- **Unison version**: 2.48.4

Everything went fine 👍

**Comment by tleedjarv** [comment]
Thank you for the report.

I am inclined to think that this issue is related to running on 32-bit platform.
@gdt please add the feedback label.

**Comment by gdt** [comment]
@jgupta Can you tell us the requested details?   You said git master, but ocaml version?  Number of files in the full set vs the two halves?  Does this get the issue only on initial sync, or when resyncing things that have not changed?

@skjardenCode Thanks for the data point.

If this is on a 32-bit CPU type, and the number of files approaches 1E9, then I think we can relabel it a "lack of check for integer overflow" or "unison should use a longer type" error.  Otherwise, we need to keep figuring out what's happening.

**Comment by jgupta** [comment]
Number of total files at present are 120801001
unison version 2.51.3 (ocaml 4.05.0)
CPU: Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz
OS: CentOS Linux release 7.8.2003 (Core)

**Comment by gdt** [comment]
Thanks, but what CPU architecture is ocaml and unison compiled with?  (One can run x86_64-capable CPUs in i386 mode.)   It might be that we have trouble with 1E9 files even on x86_64, and if so that's very interesting.

If you are able to construct a test that tries to sync 999999500 files, and see if that works, that's very interesting (or bisect if you are really in the mood).

**Comment by jgupta** [comment]
Both unison and ocaml were complied on the same CPU and OS. How do I check CPU architecture?

I am so sorry, won't be able to do tests now.

**Comment by gdt** [comment]
Basically "file /usr/bin/unison" or wherever it is and paste the output.

Two examples:
```
/usr/pkg/bin/unison: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /usr/libexec/ld.elf_so, for NetBSD 9.0, compiled for: earmv7hf, with debug_info, not stripped
/usr/pkg/bin/unison: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /usr/libexec/ld.elf_so, for NetBSD 8.2, stripped
```

**Comment by jgupta** [comment]
/usr/local/bin/unison: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=4f11de8ff9e2ca684609cd70302a947b88e7118e, not stripped

**Comment by gdt** [comment]
Thanks.  The plot thickens, but perhaps there is serialization to 30-bit types somehow.

**Comment by tleedjarv** [comment]
@jgupta if you are syncing between two machines then please provide the output from the other machine as well.

**Comment by tleedjarv** [comment]
I think I have discovered the cause of this issue. Certain integers are encoded in 4 bytes on the wire (on all platforms). RPC message ids are encoded like this. But these ids are always capped well below 31 bits, so 4 bytes are guaranteed to be sufficient.

Also RPC message lenghts are encoded the same way. I thought that RPC messages never get so big as to exceed length encoded in 32 bits, but I was mistaken. It appears that with 120 801 001 updates it is realistically possible for a single RPC message to become bigger than 4 GB.

If a single update record is serialized on average in 36 bytes then the entire list of updates is serialized in 120 801 001 * 36 = 4 348 836 036 bytes (4.05 GB), a length which requires 33 bits to store.

The debug log from the original issue report confirms my suspicion that it is the list of updates that becomes larger than 4 GB serialized.

It is a bug for sure, but I don't know if fixing it is worth the effort. The bug is exposed only under extreme conditions that should normally be avoided for the user's own good (the server process would have to have memory usage in excess of 8 GB and the client process probably in excess of 12 GB or even 16 GB just to collect the updates!). Splitting the updates with `path` preference (or by other means) is typically the suggested way.

That said, I think there is potential for a workaround (I wouldn't call it a fix). The length of an RPC message is always encoded in 4 + 1 bytes. 4 bytes for the actual integer value and 1 byte as the checksum (validation of this checksum is what causes the error message visible in the original issue report). In total there are 40 bits sent on the wire. The workaround would use some bits from the checksum byte for the integer value, thereby extending the range of possible integers at the cost of checksum space.

In short,
 * integer values that fit within 32 bits continue to be encoded exactly as today; no break in backwards compatibility.
 * integer values that fit within 33 bits (8 GB) or 34 bits (16 GB) encode 32 bits exactly as today with the remaining 1 or 2 bits encoded within the checksum byte. The checksum is then reduced to 7 or 6 bits which is probably more than sufficient. However, there has to be a way to indicate that this new scheme is in operation. This means using at least 1 or 2 more bits. This will leave us with anything from 33 bits for the value + 1 bit for the flag + 6 bits for the cheksum to 34 bits for the value + 2 bits for the flag + 4 bits for the checksum.

How would this work? If the length checksum check fails at the receiver then it checks the flag bit (or bits) to determine whether to try again with the new decoding and cheksum algorithm. It is important to note that this check and application of the new algorithm is done _only_ if the primary checksum verification fails.

I'm happy to get opinions on whether to try this approach. A blunt, but perhaps entirely reasonable, alternative is to fail with a more descriptive error message when trying to encode an integer that doesn't fit in 32 bits.

**Comment by gdt** [comment]
I am really not inclined to add a kludgy workaround.  I could see us having a feature to change the protocol to make a lot of 32-bit fields 64-bit.  I could see error checks to fail earlier with a better error message.  I could see sending two messages that each fit.  But stealing checksum bits seemsreally not helpful in the grand scheme of things.

Overall, I lean to detect and error out with a better message.

**Comment by bcpierce00** [comment]
Agree. 

       - Benjamin
