### ISSUE TITLE
Initiial sync of 650,000 files in text UI can use 5kB per file, exhausting 4G of memory

### ISSUE THREAD

**Issue by powertoaster** [bcpierce00/unison#352]
server started
Unison failed: Uncaught exception Out of memory
Raised at file "./lwt/lwt.ml", line 135, characters 12-13
Called from file "list.ml", line 73, characters 12-15
Called from file "./lwt/lwt.ml", line 31, characters 2-37
Called from file "./lwt/lwt.ml", line 83, characters 17-46
Called from file "./lwt/win/lwt_unix_impl.ml", line 239, characters 6-40
Called from file "./remote.ml", line 1465, characters 11-57
Called from file "./ubase/util.ml", line 170, characters 6-9
Called from file "./main.ml", line 131, characters 4-9

I have used this for a while now and not having any problems, then today on a new windows server I am getting this.
It may be related to the large number of files I am trying to sync but it is not orders of magnitude larger than the others.

I am doing a socket transfer between two Windows servers:

c:\unison\unison.exe C:\dir\subdir -prefer C:\dir\subdir   socket://1.1.1.1:2222/

**Comment by gdt** [comment]
Please explain what version, what ocaml version, and how big your roots are (#files).

**Comment by gdt** [comment]
See #378

**Comment by tleedjarv** [comment]
@powertoaster You are using a rather old version. Could you test again with latest Unison code (2.51.3rc1 at the moment)?

How much available memory do you have on servers before running Unison? Could you also try to track Unison memory usage while the process is running? The root size of almost 650,000 files should not be any problem at all memory-wise.

**Comment by tleedjarv** [comment]
As I had already built a test setup with 1.5 million files to investigate another issue, I gave it a go over a socket to try to reproduce this issue.

Memory consumption does increase constantly (unlike when testing between folders on the same machine). This seems to suggest that there might be a memory leak somewhere in the remoting code. Still, it is not enough to cause an Out of memory exception, unless you have very little available memory on your Windows servers.

I also tried running Unison with `repeat` (with new updates being constantly created) to see if available memory would eventually be exhausted. Interestingly, that does not happen. Once the maximum allocation has been reached, true, it is not released while Unison is still running, but subsequent syncs appear to be using the same memory and never allocate more.

It currently seems that this issue is the result of having very little available memory on the servers and the real issue is #378. The reporter mentions hitting the problem on a new Windows server, which would explain the change in memory available to Unison.

**Comment by powertoaster** [comment]
I will check and report on he memory availability for the destination server, but If I remember correctly there was 4GB available at the time of the transfers. Another piece of the puzzle might be that the majority of these 65,000 files were fairly large (several megabytes each) PDFs.  
My target server was a new Windows server that had not previously been used for anything.

**Comment by gdt** [comment]
@tleedjarv Do you have a sense of how many bytes/files are needed, compared to what you might expect from reading the code?   This is feeling like at least 3 kB per file, which seems more than I would expect, not having read the code.

**Comment by bcpierce00** [comment]
I don’t remember how many bytes are for what, but note that there is an MD5 hash in each one of these...

**Comment by tleedjarv** [comment]
If think the maximum actual consumption I ended up with was roughly 4 kB per file. That would mean 2.5 GB for 650,000 files. Just scanning the updates is less than 1 kB per file (don't remember exact numbers), but that depends on file name lengths.
I planned to investigate the code to see where the memory is allocated.
MD5 hash is 16 bytes, I think. That is not a lot.

**Comment by bcpierce00** [comment]
Maybe some data structure in the GUI?

**Comment by tleedjarv** [comment]
> Maybe some data structure in the GUI?

Yes, that's would be the first suspect for me as well, but I'm doing all testing with pure text UI.

**Comment by powertoaster** [comment]
My average files size was 6mb some but ranged up to 20mb.
I am using a strictly text UI, and the issue was definitely on the initial
transfer, which was going from a populated dir structure to a completely
empty one.

**Comment by tleedjarv** [comment]
Thank you, @powertoaster. I think we have a confirmed issue now. 4 GB is most likely just not enough for roots of this size.
@gdt I think you can remove the feedback label.

**Comment by tleedjarv** [comment]
@powertoaster there is one potential memory consumption fix in PR #402. If this scenario is still relevant to you and if you still have the possibility to test it, you may want to try PR #402. You can download binaries directly from GitHub https://github.com/bcpierce00/unison/actions/runs/311264574 and then make sure you run the text UI (add `-ui text` if necessary).

**Comment by tleedjarv** [comment]
I think the suspicion was correct, this and #780 have the same underlying cause.

The cause is that all the transport threads (Lwt threads, not real threads) are created together and queued up for eventual execution. This of course is wasteful in itself but the major problem with this approach is that none of the completed threads are collected by GC until _all_ threads are completed.

The number of transport threads is the same as the number of updates to sync, plus there are many waiting threads generated internally by Lwt to limit the number of concurrently running threads. With hundreds of thousands and millions of these threads and their data uncollected, it is easy to exhaust gigabytes of memory. If you do have memory to spare then eventually the stack space will be exhausted.

There have been several patches merged already that reduce the overall memory requirement. The 4-5kB per file, as in the issue title, is probably no longer accurate, but fixing this issue still has the potential of further considerably reducing the memory need (I've already verified this with some fix prototypes).

**Comment by gdt** [comment]
It seems making one thread per item up front is bad strategy, compared to creating them in a generator as needed and having only a reasonable number live.  I'm guessing you're doing something like that, or using a worker thread pool to deal with the state and letting a worker thread do more than one thing.

**Comment by tleedjarv** [comment]
> It seems making one thread per item up front is bad strategy

Agree. This is what probably causes the stack overflow in #780. This, plus not collecting completed threads is what causes overall high memory usage.

> compared to creating them in a generator as needed and having only a reasonable number live. I'm guessing you're doing something like that, or using a worker thread pool to deal with the state and letting a worker thread do more than one thing.

Doing this properly without any (theoretical) performance regressions is a big task. I had a very simple prototype for this but it could produce some worker starvation in certain situations (maybe not an issue in practice) so I dropped it. I don't plan to do any major work in this area at the moment but it may be a good idea eventually.

In the meantime, I have another very simple prototype that still creates all threads up front but allows GC to collect completed threads and that won't change any performance characteristics. I'm still contemplating whether to open a PR or not. I've measured memory use reduction around 1 kB per file, so most users wouldn't notice nor care. Why risk breaking something?

**Comment by gdt** [comment]
Agreed that the last thing you mention doesn't seem to have a favorable benefit/risk, especially for the next release.

How about opening a fresh PR that explains what's going on in the code in terms of creation and freeing timing, now that we understand, and I can close this as a dup?  That way we have a clear problem statement for whoever picks this up eventually.   I don't mean to criticize this issue; it served to figure out the root cause, but now that we (you!) can point to the code and explain why it leads to too much memory use, how we got here isn't relevant any more.

**Comment by gdt** [comment]
There have been a lot of improvements since the last confirmation, specifically #809, so I'm going to ask to test against the head of git.   Probably, if there are problems, it would be good to open a new issue with crisp details and close this one, unless what's in this issue is basically all true, in which case a comment with fresh tests that makes that case would be good.

**Comment by gdt** [comment]
Feedback timeout.   Please feel free to open a new issue with a repro recipe with 2.53.1 or newer.
