### ISSUE TITLE
unison wire protocol depends on unison minor release

### ISSUE THREAD

**Issue by gdt** [bcpierce00/unison#407]
As an example, 2.51.x and 2.51.y are compatible, but 2.48.x and 2.51.y are not.

This issue is not about ocaml; see #375 and #377.

This issue is really about how the wire protocol should be able to be extended for future versions without becoming incompatible.

(Please do not add comments that you have this problem too, or that some packaging system has an old version.  The problem is well understood and packaging system choices are out of scope for the unison issue tracker.)

**Comment by mvglasow** [comment]
Totally agree. For versions up until now, we will likely have to stick with program version = protocol version. For future versions, we need to establish an convention for version numbers. For example, the protocol version could take its number from the program version in which it was introduced.

When a new version is released, one out of two things should happen to the protocol version:
* If no changes have been made to data structures which go across the wire, keep the protocol version (i.e. same as in the previous program version)
* If changes have been made, increase the protocol version.

Bonus would be to have a compatibility mode, enabling a newer version to fall back to an older protocol version when the peer is an older version.

Unison would then also need to report the (latest) wire protocol version it supports, along with its program version. Ideally, the wire protocol itself includes its version somewhere in the header, so two peers can immediately determine whether both speak the same version.

As long as we still have dependencies on the OCaml version (see #375), we might want to include that in the protocol version as well. That way, we can at least give the user a meaningful error message. Something like:

    Incompatible protocol versions: local supports 2.56-ocaml4.10, but remote supports only 2.58-ocaml4.11

rather than the present “marshaling error, maybe the two clients were build using different OCaml versions”.

**Comment by mvglasow** [comment]
Also, we should then somewhere maintain a list of official version numbers, as well as a mapping between program versions and protocol versions they support (if that cannot be inferred directly).

**Comment by gdt** [comment]
> As long as we still have dependencies on the OCaml version (see #375), we might want to include that in the protocol version as well. That way, we can at least give the user a meaningful error message. Something like:
> 
> ```
> Incompatible protocol versions: local supports 2.56-ocaml4.10, but remote supports only 2.58-ocaml4.11
> ```
> 
> rather than the present “marshaling error, maybe the two clients were build using different OCaml versions”.

Good point.  Filed as #444.

**Comment by karger** [comment]
I'm finding the current version wire protocol even seems to be incompatible with itself.  I've download unison-v2.51.3+ocaml-4.08.1+x86_64.windows, run a socket server, launched the gui on the same machine and attempted to connect to the socket server, and gotten a server disconnect "possibly because client and server have been compiled with different versions of the OCaml compiler".   Tried again with unison-v2.51.3+ocaml-4.11.1+x86_64.windows and had the same problem.

**Comment by tleedjarv** [comment]
@karger This is a different issue (see #435 for one of the reports). It is already fixed but the fix is not yet in a release. It will come in the next release.

**Comment by gdt** [comment]
While a real fix is on the horizon, we have decided to refrain from making protocol breaks in 2.51, and to defer until a post-negotiation world changes that would require  a break.   So I'm calling this particular issue resolved.
