### ISSUE TITLE
Setting unison profile directory does not change all paths

### ISSUE THREAD

**Issue by BlivetWidget** [bcpierce00/unison#463]
Hello,

I'm trying to run Unison in a portable manner on Windows10.  It seems I should be able to do this with a batch file containing:

```
SET UNISON=.\profiles
".\bin\unison-gtk2.exe"
```

And everything seems to run fine, from selecting the profile to checking the directories.  However, when pressing "Go", the program fails because it is looking for "unison.log" in .\profiles (as I told it to), only it thinks .\profiles is in my user directory, instead of the local .\profiles where the batch file is located.

```
In callback for signal clicked, uncaught exception: Util.Fatal("Error in getLogch:\nC:\\Users\\shane\\.\\profiles\\unison.log: No such file or directory")
Raised at file "./ubase/util.ml", line 209, characters 6-17
Called from file "./ubase/trace.ml", line 177, characters 13-23
Called from file "./uigtk2.ml", line 674, characters 2-28
Called from file "gtkSignal.ml", line 62, characters 18-35
```

Is there a command I forgot in my batch file, or is this a bug?  Thanks for your help.

**Comment by tleedjarv** [comment]
Did you try with the latest version from GitHub? If not, please download the latest release candidate from the releases page. This was fixed just recently.

**Comment by BlivetWidget** [comment]
@tleedjarv I believe this is the latest available version (unison-v2.51.4_rc1+ocaml-4.05.0+x86_64.windows).

**Comment by tleedjarv** [comment]
Yes, this is a latest version.

I have verified the error and I would argue it is a bug, but not everyone might see it this way.

This is what happens:

1. Unison derives the log file path by concatenating the "unison dir" (in this case the `UNISON` env var) and file name "unison.log"; unless overridden by "logfile" preference.
2. If the log file path from previous step (that is, either the derived one or the overridden one) is a relative path then the relative path is resolved in reference to the "home dir", which is derived as follows: in Unix/Linux/Cygwin from `HOME` env var; in Windows from `USERPROFILE` env var if it exists, `UNISON` env var next, and if neither exist then `C:\`.

This is where I would argue the bug is. That the relative path is resolved in reference to the "home dir". The log file is the only path that gets this treatment. It could be resolved in reference to the current working dir. Before fixing this as a bug, I would like to hear more opinions.

As a workaround, you could try setting `USERPROFILE` to `.` (current dir). Disclaimer: I don't know if it will work. I don't know what side-effects it will have. And you should make sure you alter this env var only for the unison process, not globally.

**Comment by BlivetWidget** [comment]
@tleedjarv 

Thanks for your help in explaining the underlying behavior.  While I agree this is a bug, your explanation allows for a workaround.

```
SET USERPROFILE=.\
SET UNISON=%USERPROFILE%\profiles
".\bin\unison-gtk2.exe"
```

Using SET, changes are not permanent and this appears to behave in the expected manner with no side effects.  Of course, in this case there is no need to set the UNISON variable other than aesthetics (I simply prefer the descriptive "profiles" to ".unison").

**Comment by gdt** [comment]
Why is it sensible to have UNISON set to a relative directory?  Should that be an error?   That seems to set up a world where there are many such directories depending on where you run the command.   I am inclined to prohibit that, and make anyone who wants to have multiple directories have a wrapper that sets absolute paths.  But perhaps I'm missing understanding some reasonable usage.

Separately, I think I agree that it makes sense for paths to be relative to $UNISON, and not have any further processing.

**Comment by tleedjarv** [comment]
> Separately, I think I agree that it makes sense for paths to be relative to $UNISON, and not have any further processing.

I was investigating the code a little and I am going to create a PR which does exactly that. Unison used to put several files in $HOME, but that should no longer be the case for any of those.

**Comment by BlivetWidget** [comment]
My desire to use a relative path in setting the UNISON directory comes from my usage pattern, I suppose.  I place Unison on the external drives and run them from there, back and forth between other locations.  In effect, the drive is the master, rather than an individual computer.  Setting a relative path just makes it easier to copy this system onto multiple drives without making other changes.  Probably the typical use case is to have a single home base on a computer.

Regardless, I think tleedjarv's change is the right move.  So if I'm understanding correctly, after this change my batch file could look something like the following (where I am storing the profiles directory alongside the other unzipped contents):

```
SET UNISON=%~dp0\profiles
"%~dp0\bin\unison-gtk2.exe"
```

**Comment by tleedjarv** [comment]
> ```
> SET UNISON=%~dp0\profiles
> "%~dp0\bin\unison-gtk2.exe"
> ```

Yes, that should then work. But also this, like you originally tried:

> ```
> SET UNISON=.\profiles
> ".\bin\unison-gtk2.exe"
> ```

**Comment by gdt** [comment]
I see your point about use of relative paths, and withdraw my suggestion that we disallow it.
