### ISSUE TITLE
unison-gtk2 2.51.3 not running on macOS Catalina (missing external library?)

### ISSUE THREAD

**Issue by zudljk** [bcpierce00/unison#467]
OS: macOS 10.15 Catalina

* Installed gtk using `brew install gtk+`
* Downloaded unison-gtk2 package: unison-v2.51.3+ocaml-4.11.1+x86_64.macos-10.15.tar.gz
* Installed into /usr/local/bin using 
  `sudo install -m 755 <path-to-extracted-package>/bin/unison-gtk2 /usr/local/bin/unison-gtk2`
* Ran `/usr/local/bin/unison-gtk2`
* Expected behaviour: Unison GUI opening
* Actual behaviour: The application outputs the following message and terminates:
```
    dyld: Symbol not found: _g_cclosure_marshal_VOID__POINTER
       Referenced from: /usr/local/bin/unison-gtk2
       Expected in: /usr/local/opt/gtk+/lib/libgtk-quartz-2.0.0.dylib
     in /usr/local/bin/unison-gtk2
    zsh: abort      /usr/local/bin/unison-gtk2```
```

**Comment by gdt** [comment]
Note that the required libraries for the mac GUI builds are not documented.  Hence this not working is not a failure to meet specifications :-)   Help documenting the plan is welcome.

As an observation, right now there appears to be no one actively contributing to unison who both has a macOS machine and uses the GUI.   Fixes and doc improvements are always welcome.

**Comment by zudljk** [comment]
Not that I‘m not trying to build the GUI, I‘m just trying to run the GUI.
I‘d be glad to contribute to the documentation, but how can I find out which library is missing?

**Comment by khituras** [comment]
I have the same issue.
To me, it seems that the question is not so much which library is missing but which version. Because the GTK+ library is there (when installed view homebrew; MacPorts would install the library in another directory) but it's using an unknown symbol.
So my guess is that we would need an older version of of homebew's GTK+ library. Unfortunately, I wasn't able to install an older version, I cannot even find a list of old versions. Perhaps they are not even available any more which would effectively break the GTK2 binary on newer MacOS systems (but I don't now for sure).

On the upside, I found the compilation of Unison into a Mac app quite easy (Xcode & CLI tools must be installed):

```
brew install gtk+
cd <some dir where we can clone unison to>
git clone https://github.com/bcpierce00/unison.git
cd unison/src
make
open uimac/build/Default/Unison.app
```

**Comment by gdt** [comment]
This is a dup of #440.   Running a prebuilt binary with different libraries from the build environment is unsound, so there's no hope for joy without that being documented first.
