### ISSUE TITLE
Windows build: v2.51.3_rc2 and later do not ship unison-fsmonitor

### ISSUE THREAD

**Issue by winny-** [bcpierce00/unison#500]
It appears the Windows build v2.51.3_rc2 and later does not ship unison-fsmonitor.  I think this might be necessary for the `-repeat watch` option.  In the meantime the older versions do ship the unison-fsmonitor tool, and work fine.

```
PS C:\Windows\Temp\unison-v2.51.3_rc2+ocaml-4.05.0.windows\bin> .\unison.exe .\a .\b -repeat watch -fastcheck true
Unison 2.51.3 (ocaml 4.05.0): Contacting server...
Looking for changes
Reconciling changes
Nothing to do: replicas have not changed since last sync.
Fatal error: No file monitoring helper program found
PS C:\Windows\Temp\unison-v2.51.3_rc2+ocaml-4.05.0.windows\bin> ls *.exe


    Directory: C:\Windows\Temp\unison-v2.51.3_rc2+ocaml-4.05.0.windows\bin


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         14-Apr-21     15:37        5556736 unison-gtk2.exe
-a----         14-Apr-21     15:37        2853888 unison.exe

```

**Comment by gdt** [comment]
It would be great if you or someone(tm) could figure this out and submit a PR.

I haven't marked this defect, because the CI builds are for CI, and them not being like people would like isn't therefore a bug in a formal sense.  However, if the Windows build when done according to the instructions fails to build this, that seems like a bug.  Either way, improvements are most welcome.

**Comment by tleedjarv** [comment]
The PR for building and packaging is #493.
There seem to be some reports of hangs with unison-fsmonitor on Windows, but no clear cause is known yet.

**Comment by gdt** [comment]
Now they do
