### ISSUE TITLE
Weird behaviour of -ignore and -ignorenot

### ISSUE THREAD

**Issue by Babber** [bcpierce00/unison#516]
Hi,
I try to sync certain files in a folder ignoring all other files and ignoring all subfolders. So basically I would like to ignore everything in the given folder `/path1/` except for files that match some filters. One of my first naive attempts was something like this:
`unison "/path1/" "/path2/" -force "/path1/" -ignore 'Name *' -ignorenot 'Name *.css'`
When I run this, I always get `Nothing to do: replicas have not changed since last sync.` even if it's not true.
At the same time,
`unison "/path1/" "/path2/" -force "/path1/" -ignore 'Name *' -ignorenot 'Name *'`
copies everything as expected, but I couldn't reverse-engineer what could I possibly "ignorenot" to get only the files I need.
When I try to `-ignore 'Regex *'` or `'Regex */*'`, I get `Malformed pattern "Regex *".`
Currently, my best solution is to ignore all subfolders separately as in `-ignore 'Regex sub1/*'`, `-ignore 'Regex sub2/*'` etc... This is not ideal, because the subfolders number and name can also change.
I was not successful with `Path` and `BelowPath` either.
The above behaviour seems somewhat inconsistent to me, also after trying to find an explanation in the manual. If this is a bug, a fix would be appreciated.
And in the meantime, is there any way to practically filter out everything in a folder except the files that match some filter like `*.css`?
Any help is much appreciated, many thanks!

**Comment by gdt** [comment]
Reading the 2.48 manual, what you are experiencing is not a bug.   Of course, you should be using recent 2.51 and reading the 2.51 manual even if you have to read it in source code form :-)    (Arguably the ignore/ignorenot mechanisms are difficult to understand, but it's far from obvious what other mechanisms should be provided instead.)

The github issues tracker is only for bug reports and enhancement requests (that are clear enough to be likely implementable and of broad interest, so that them  being present in the tracker is a net win for the developer community).     Please ask for help on the unison-users list, and/or propose/discuss significant changes on unison-hackers. 

See https://github.com/bcpierce00/unison/wiki/Mailing-Lists for how to join the lists.

**Comment by Babber** [comment]
Fair enough. I thought it might be a bug.
Anyway, thanks for the quick response!
