### ISSUE TITLE
Unison changed download URL path and archive format

### ISSUE THREAD

**Issue by reagle** [bcpierce00/unison#560]
The unison brew updated to 2.51.4 and so I also changed the version on my webhost, but I can then no longer use the gui version provided by the cask. I tried to update the cask but the following fails because the [releases](https://github.com/bcpierce00/unison/releases) download URLs now look like: `https://github.com/bcpierce00/unison/releases/download/v2.51.4/Unison-v2.51.4.ocaml-4.12.0.macos-10.15.app.tar.gz`.

```
brew bump-cask-pr --version 2.51.4 homebrew/cask/unison
...
==> Downloading https://github.com/bcpierce00/unison/releases/download/v2.51.4/Unison-2.51.4.OS.X.
#=#=#
curl: (22) The requested URL returned error: 404
Error: Failed to download resource "unison"
Download failed: https://github.com/bcpierce00/unison/releases/download/v2.51.4/Unison-2.51.4.OS.X.zip
```

**Comment by gdt** [comment]
CI binaries are for CI, and it's a bonus if they are useful for others.

Fixing the OS name in the filenames doesn't seem like a bug.  Please feel free to file a bug with apple for renaming their OS :-)

As to why it used to be zip, I can't say.  .tar.gz seems like a reasonable choice now.

Please address homebrew issues to homebrew.  This project does not provide support for packaging system users.  But, it sounds like this is a simple issue for homebrew to fix.

(All that said, I find it surprising that homebrew is using our CI binaries instead of building from source, but that's out of scope for this project.)
