### ISSUE TITLE
broken TOC links in unison-manual.html

### ISSUE THREAD

**Issue by olafhering** [bcpierce00/unison#610]
The links in the TOC have no target, there is no `#news` for example. Unclear when it broke.

**Comment by gdt** [comment]
The doc build seems fragile; I already found that it depends on lynx even though that isn't (wasn't) documented.   I assume you are talking about the html in the doc branch, and I'm curious if "make docs" from sources gets working toc links for you.   I have some dim memory of trouble with hevea, which seems to be a boutique tool.

**Comment by olafhering** [comment]
I have noticed it with a local build, 5c9d03550316a4115cd1a158333703d85337d7f2 appears to be broken as well.
Does it have to be hevea? It seems there are also other tools to turn tex into html. But, I have no experience with any of that.

**Comment by gdt** [comment]
Thanks for confirming your local build, presumably not on NetBSD, so that means it isn't just me.

I don't think there is any rule that we have to use hevea, and I'd be happy to look at a PR to use some other tool, as long as it doesn't introduce a non-portable or difficult language dependency (e.g. haskell, java, rust).    We could also consider changing the docs entirely to markdown or texinfo, but there's a big pipeline of docs to strings.ml.   Anything more than bug fixes likely best proposed on -hackers.

**Comment by gdt** [comment]
The problem still exists.  E.g. the People TOC entry links to #people, but the id on the section is "sec4" instead.
