### ISSUE TITLE
Identify directories by the directory itself and not it's full path

### ISSUE THREAD

**Issue by jsbmg** [bcpierce00/unison#615]
Possible feature request: I'm writing a program that invokes Unison, where the full path of the two directories is subject to change. For example, one directory is inside a changing temporary directory:

`Unison $root1 $root2`

Where:
`root1: $HOME/syncfolder`
`root2:/tmp/xdfka8/syncfolder` (where `xdfka8` changes every invocation but for all intents and purposes `syncfolder` is the same)

This will always assume the directories are different because the root path of `root2` will always be changing, even though the top level directory itself is the same (or slightly modified). I've looked at the `rootalias` option but it looks that requires persistent paths as well.

Is there a way for Unison to recognize folders even if their full paths are ephemeral?

**Comment by acolomb** [comment]
You should be able to cover that use-case with the `rootalias` option.  It basically rewrites part of the path before calculating archive names.  Have you tried that?  If so, how did it fail?

**Comment by gdt** [comment]
This seems to be not in scope for the  issue tracker; please feel free to ask for help or discuss on the mailinglist.

**Comment by tleedjarv** [comment]
I think this is a valid feature request. Reopen?

**Comment by tleedjarv** [comment]
This looks like a special case of `rootalias` (conceptually, at least) and in my mind also makes sense with changing mountpoints or removable media (there is a `mountpoint` preference but this, like `rootalias`, does not work in the provided case). It does make sense as a feature request (in fact, with drive letters in Windows, how is this not a requirement?). It's also at least somewhat related to #588 the way I see it (although there is an additional different underlying issue with #588).

**Comment by tleedjarv** [comment]
Initially I thought `rootalias` does not work in this situation but it actually does. It's a workaround but it should solve your issue.

@jsbmg you can try this. For every invocation of `Unison $root1 $root2` you construct rootalias on the fly. You can see the format of the canoncial root by using the `-showarchive` option but basically it is `//hostname/realpath` (`//hostname//tmp/xdfka8/syncfolder`, for example).

The trick is that the right-hand side of rootalias does not have to be a valid root. You could choose a constant name that is meaningful to you and then use it every time you invoke Unison with a unique path name.

For example, run 1:
`Unison $HOME/syncfolder /tmp/xdfka8/syncfolder -rootalias "//localhostname//tmp/xdfka8/syncfolder -> syncroot2"`
Run 2:
`Unison $HOME/syncfolder /tmp/ogmkfg/syncfolder -rootalias "//localhostname//tmp/ogmkfg/syncfolder -> syncroot2"`
Run 3..n:
`Unison $root1 $root2 -rootalias "//localhostname/$root2 -> syncroot2"`

Since there is a very simple recipe of constructing the `rootalias` from `$root2`, which you know anyway, this can be fully automated.
