### ISSUE TITLE
windows-2022 CI build fails

### ISSUE THREAD

**Issue by gdt** [bcpierce00/unison#634]
This is perhaps a problem with the GHA support of ocaml.  For now, our windows CI will be windows-2019 only.

For now, this is not identified as a unison bug.

**Comment by tleedjarv** [comment]
The error message can be seen here:
https://github.com/bcpierce00/unison/runs/5134460381?check_suite_focus=true#step:41:3

The message suggests that `This problem is probably due to using incompatible versions of the cygwin DLL.` and this is likely correct. In the same error message it can be seen that `D:\cygwin\bin\tar.exe` (from Cygwin install) executes `C:\msys64\usr\bin\zstd.exe` (from pre-installed MSYS2) and that's probably the cause of the incompatibility. This happens even though zstd is installed by Cygwin: https://github.com/bcpierce00/unison/runs/5134460381?check_suite_focus=true#step:7:161

Why this is happening and how to fix it, I have no idea.
