### ISSUE TITLE
%system can not be used to detect the system

### ISSUE THREAD

**Issue by olafhering** [bcpierce00/unison#657]
[This discussion](https://discuss.ocaml.org/t/a-zoo-of-values-for-system/8525) revealed `(enabled_if (= %{system} "linux"))` can not give the expected result. Specifically, building works for x86 and aarch64, but not ppc:

````
[   37s]      ; architecture = "arm64"
[   37s]      ; model = "default"
[   37s]      ; int_size = 63
[   37s]      ; word_size = 64
[   37s]      ; system = "linux"
````
````
[   44s]      ; architecture = "power"
[   44s]      ; model = "ppc64le"
[   44s]      ; int_size = 63
[   44s]      ; word_size = 64
[   44s]      ; system = "elf"
````

**Comment by gdt** [comment]
Can you point to where in unison this is used and what happens on which platform, vs what should?  I think I can follow but I'm not sure.

**Comment by olafhering** [comment]
`git grep enabled_if`, it is used in `fsmonitor`. I have an idea how to easily address it.

**Comment by gdt** [comment]
OK, happy to review a PR.   (It seems this really should be conditional on having some particular syscalls, not the name of an OS, but perhaps they are sufficiently non-portable that it is equivalent today.)

**Comment by tleedjarv** [comment]
This is pure Linux stuff. It will also compile and work on SmartOS and OmniOS because Linux syscalls are offered as a compatibility layer, but that is not relevant here - the target is only Linux. Besides, there is a separate fsmonitor implementation for the other two (and others in that family).

I actually think that it is a big upside that we don't have `./configure`. (dune builds may eventually require some lightweight alternative that could probably be scripted in OCaml or sh)

**Comment by gdt** [comment]
configure is certainly messy so I see your point, but I don't like ifdef OS when it should be a feature test (which may not be this case).

I don't understand why code that uses Linux syscalls can't build and work on any system that supports those syscalls.   While these might not be in that category, it's been very normal for Unix systems to support syscalls originated in some other variant, either before adoption into POSIX, or just as an aligned extension for things that appear not headed to POSIX.

So build systems really need some way to say "if syscalls X and Y are supported".

However, that's off topic from how this bug probably should have been written "building on GNU/Linux ppc64 should build fsmonitor for Linux but doesn't", and I'm happy to merge a reasonably clear point fix for that.

**Comment by olafhering** [comment]
I think `enabled_if` needs a bool, which is provided by an external command. There is `read:file` in recent dune (3.x?) versions, which could be used.
Another possibility is to generate and use `include file`, it is unclear if this will actually work.
A third way is to put `package` into `dune-project`. This allows to specify which targets are supposed to be build. `dune build @install -p unison,unison-gtk2[,unison-fsmonitor] && dune install unison unison-gtk2 [unison-fsmonitor]` will become the required command to optionally skip fsmonitor.

With the third approach it is required to remove the `enabled_if` commands. This means fsmonitor may fail, depending on the target. We could reduce the potential of failures by using `enabled_if (or (<> system=macos) (<> system=win32))`

Regardless how `enabled_if` will be changed, a proper `dune-project` should exist anyway. I will propose this in a separate PR.

**Comment by tleedjarv** [comment]
No to `enabled_if (or (<> system=macos) (<> system=win32))` because that does not equal Linux.

The dune build process for Unison is unmaintained. It is kept "working" in the sense that it doesn't break in the CI and opam, but that's really it. The primary build process is still using makefiles (and even that is barely maintained). It would be great if someone could improve and maintain the dune build process, too, but I don't see that happening. Perhaps the solution is just to replace dune build instructions in the opam file with `gmake`?

**Comment by olafhering** [comment]
well, my goal (for this decade) is to get rid of `make`. thankfully there are a couple of years left to hash this out. :-)

**Comment by tleedjarv** [comment]
@olafhering can you capture the output of `uname` and use that in `enabled_if`?

**Comment by olafhering** [comment]
Not that easy, and uname might be the wrong tool for cross compilation.

[Maybe someone in the forum has an idea.](https://discuss.ocaml.org/t/example-for-enabled-if-system-in-dune-files/9440)

**Comment by tleedjarv** [comment]
Is cross compilation some hypothetical future possibility or is it actually working?

I feel that now we're getting a bit off topic but, just theoretically, couldn't you in that case have something along the lines of `if cross-compiling then A else B`?

**Comment by gdt** [comment]
I really doubt cross compiling works, but all things should be cross compilable and if not its a bug.   I don't want to introduce things that move us farther from that (even if I don't want to dig in to fix it).

I still don't understand why it's ok to depend on the OS, instead of some set of detected syscalls, and if we do need to depend on OS, then that should be determinable by some test compilation of a header/ifdef.   I have no idea how to do that with dune, but those sorts of tests are obviously needed in any build system.

Also, it seems this is really an upstream bug in ocaml or someplace, to flip the os name (presumably for the target) to elf vs linux depending on CPU type.

**Comment by tleedjarv** [comment]
I agree, this is an upstream bug.

As to depending on OS vs tests. The issue here is not about syscalls. See below.

> if we do need to depend on OS, then that should be determinable by some test compilation of a header/ifdef.

Yes, 100% this.

But the issue is not on the C side. That's why detection tests and ifdefs don't solve the issue in this case.

The real issue is that fsmonitor's OCaml code is OS-specific, not just the C code.  The C code is just very thin stubs over the syscalls, making the OCaml code also OS-specific. It's the combination of OS-specific OCaml code on top of OS-specific C code that provides the platform-neutral API for the common fsmonitor code.

The dune test is present to enable/disable building the OS-specific OCaml code.

The alternative could be to drop these OS-specific bits (both OCaml side and C side) and replace them with a platform-neutral fswatcher library (I think one or two exist in the wild...). This way the OCaml code would not have any OS dependencies. And this is a huge effort for a small bug :)

Just to be complete, I will leave you with another alternative here. But not because it makes sense, only to have all options on the table.
It is possible to have empty stubs for all fsmonitor C code that compile on all platforms (ifdefs). Then the backend selection can be done at runtime in the OCaml code. This, obviously, would be much simpler than using an external fswatcher library. But still the wrong solution to the problem at hand, in my view.

I can't believe this seemingly trivial issue is so hard to solve with `dune`. I'm sure this has been solved before. Perhaps @kit-ty-kate can help?

**Comment by tleedjarv** [comment]
I think the answer is in a thread you yourself @olafhering have started and even linked to in your post :)
https://discuss.ocaml.org/t/a-zoo-of-values-for-system/8525

The answer seems to be to use `dune-configurator`. Why not consider that?

As a side note, I can't help but chuckle at the idea that the exhaustive list of choices is Windows, Mac and Linux. Plus occasionally IOS and Android.

**Comment by olafhering** [comment]
kit-ty-kate proposed a simple solution for this. `enabled_if` just needs a list of system==X checks. The list can be constructed based on this output:
````
tr ' ' '\0' < ocaml.git/configure.ac | xargs -0n1 | grep system= | tr -d ',]' | sort -u
````
I will prepare a PR.
