### ISSUE TITLE
More beautiful interface on Windows?

### ISSUE THREAD

**Issue by treysis** [bcpierce00/unison#688]
I just switched from Unison 2.40 to 2.52, gtk-Version on Windows. Even though I never liked the interface that much, it was still okay. I was surprised how it looks even worse. Is there a way to change the theme as a user or does this have to be done at compile time? Could we get a more stylish theme?

**Comment by gdt** [comment]
Please use the mailinglist for questions.
https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests

**Comment by treysis** [comment]
It's a feature request!

**Comment by tleedjarv** [comment]
With #566 it is easy (well, supposed to be easy; I haven't tried myself) to provide a different GTK theme and even switch themes. I could consider including a different theme for Windows in that PR if one is found that works well and looks ok in Windows. But I doubt it is easy to get there... The "works well" part is especially tricky because there are no testers as it is.

**Comment by treysis** [comment]
I'd be willing to test.

**Comment by tleedjarv** [comment]
Ok, I'll hopefully soon add instructions in that PR on how to test different themes.

**Comment by treysis** [comment]
Any way to hook me up with the binaries of your test builds?

**Comment by tleedjarv** [comment]
> Any way to hook me up with the binaries of your test builds?

Go to https://github.com/bcpierce00/unison/actions/runs/1917145384 and look for "Artifacts" then find a suitable version for you from artifacts ending with "-publish".

**Comment by treysis** [comment]
Even the default theme looks great. Looking forward to the gtk3 version!
