### ISSUE TITLE
Unison only using 1 core for building archive files

### ISSUE THREAD

**Issue by muelli01** [bcpierce00/unison#776]
I am using Unison 2.51.2 for replicating huge amounts of data from video editing (18TB) with filesize of up to 10GB.
I noticed for a long time, that during archive buildup or checksum verify, Unison seems to use only 1 core of my CPU.
As I now had to re-create my archives (for reasons...) I have to wait 2 days or so for them to be created again.

Is it possible to make Unison use more/all CPU cores for checksumin/archive create?

Thanks!

**Comment by gdt** [comment]
You seem not have found https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests as you are asking about an old version and asking a question rather than reporting a bug.  Please use the `unison-users@` mailinglist for questions.

However, I was able to infer a valid feature request; see #777 and I'm therefore closing this as a blend of dup and question-not-appropriate-for-issue-tracker.   Feel free to dscuss a design on `unison-hackers@` if you wish to implement this and submit a PR.   Absent someone willing to down that path, I don't see anything happening.
