### ISSUE TITLE
Stale backup files accumulate over time

### ISSUE THREAD

**Issue by grothesque** [bcpierce00/unison#782]
It seems to me that unison has no mechanism for (eventually) removing stale backup files, i.e. backup files that are left over after the corresponding files in the replicas have been deleted.

Over time this can lead to creeping storage space usage, as well as present a potential data security problem (where files deemed to be deleted are preserved indefinitely).

A possible solution could be that unison touches backup files upon deletion (to mark the time of the deletion) and finally removes them after a preset period of time has elapsed.

**Comment by Friptick** [comment]
In fairness to `unison`, this is an issue affecting pretty much every package that creates backup files, of which there are lots, including `rsync`. I agree it's a problem. I wish Linux distros would agree on a standard implementation for a self-emptying `'backups` directory with a user-defined purge schedule. At present the user is effectively required to babysit every program individually in order to avoid the creeping bloat you describe. So silly. This would be a great project for systemd to work on.

**Comment by grothesque** [comment]
@Friptick, I think that the problem is easiest addressed from within unison.  After all unison itself knows best which files are to be synchronized.  For example, if the user initially configures the syncing of `*.a` and `*.b` files, but then turns off syncing of `*b` files, the corresponding backup files will become stale, while still present in the file system.  On the other hand simply deleting backup files of a certain age would not work as well - even an old backup can be the most recent one.

A solution independent from unison would thus require replicating (and keeping up-to-date) a lot of Unison's configuration in a different place and possibly in a different format...

Myself, I only use `backupcurr` (for 3-way-merges).  I would be happy if there was an option in unison to delete backups along with any deleted files: if I choose to delete a file, I no longer need the capacity to delete it.

A more general solution could be to keep backups of deleted files, but only for some time.  One possible implementation would be to walk the backup file tree and check the modification dates of any files that are no longer present in the replicas.  This information (when to delete which stale backup file) could be cached in the archive files under the `.unison` directory, just like this is done for the synchronization state.

**Comment by Friptick** [comment]
@grothesque Yes, you make some good points. Your solution would indeed be the optimal one.

**Comment by gdt** [comment]
It sounds like this is not a defect (failure of unison to follow specification).  It's also not really a feature request, as there isn't a crisp articulation of what should be done and why, that will be a good idea over all situations.   Because (see https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests ) the issue tracker is limited  to bugs and crisp feature requests, I'm going to close this and suggest that if you would like to discuss what a feature would look like, hoping to arrive at a specification clear enough to implement, please feel free to discuss on `unison-hackers@`.   I'll also caution you that for this to happen, someone will have to not only create a specification, but then create a pull request with code, doc changes, and tests.   I find automatic deletion extra scary, so I'll likely want more hard-core testing than usual.

**Comment by grothesque** [comment]
Thank your for the explanation.  While I sympathize with the wish to limit the number of open issues, closing them before giving the reporter a chance to react IMHO tends to drive away potential contributors.

As far as I can tell, the unison documentation (is there any other specification?) indeed does not say anything about the fate of backup files.

So, while not having a way to delete stale backup files automatically might not be a bug in the sense that unison does not meet its specification, it’s a documentation bug, since the documentation does not warn about a serious side-effect of an option: that enabling backups may (and indeed given enough time will) clog up the disk.

This is something that could be fixed easily and IMHO warrants this issue.  Would you please consider re-opening it until the documentation is fixed?

As for my above informal proposal on how the problem of stale backup files could be solved properly, I think that it could be developed into a formal specification.  But first I am keen to hear from some developers / experienced users whether the issue that I identified is perceived as a problem worth fixing.  I thought that this github issue may serve this purpose as well.  Should I rather ask on a mailing list?  Which one?

**Comment by gdt** [comment]
If you think it's a doc bug (which it may well be - I have not taken the time to dig in), please feel free to open a "Manual does not explain [foo]" bug, and we can certainly keep that open.  But there's a fine line between "what the manual says is incorrect" and "people aren't warned about something that is a clear consequence of what is stated".

Is it worth fixing?  I don't intend to spend time fixing it, because it's a feature that I don't use.   You can ask yourself if you are willing to figure it out, think about the corner cases for people using unison differently than you, and write the code.   I try hard to look at everything that is submitted as a PR, and call for review from the developer list.   I try to go over the entire open bugs list periodically, and it was around 200 when I started.   I can see why people who want a feature change (but aren't willing to define and code it) want their issue open, but there is no group of people just working on this random backlog, so the result is cognitive load for not a lot of gain.    As it may seem I'm hinting, the real issue is that the number of people who are regularly spending time on this is 2, and there are maybe 3 more that do things occasionally, all appreciated.

github is not a replacement for the developer mailinglist.  It's github's fault that they try to make it that way, and offer project hosting without mailinglist hostiing.  Other projects have acquiesced to github's implicit demands to have all interaction on github, but not this one.  (And there's an open issue to reconsider project hosting, which was there before #giveupgithub became a thing.)

**Comment by Friptick** [comment]
> It's also not really a feature request, as there isn't a crisp articulation of what should be done and why

This seems a bit disingenuous. This may not be a bug, but scheduled deletion of backups is an obvious potential feature for a tool that has the capacity to create large amounts of detritus. The sync tool that all the cool kids use, syncthing, has exactly the feature OP is groping for. Specifically, the options are "trashcan", where only the most recent backup is retained, and "keep for X days", where backups are deleted after the timeout. It all works great. If you check the syncthing tracker you'll see that the devs are notably conservative and hawkish about feature creep, which suggests that this feature is in demand. Anecdata, yes.

>I can see why people who want a feature change (but aren't willing to define and code it) want their issue open

Not everybody contributing here has the skills required for that. But your general point is taken.

Of course, this is a community project with limited resources, as you say. So no complaints. Thanks for your work.

**Comment by gdt** [comment]
Please see https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests#feature-requests which asks that only fully-defined feature requests be in the tracker.    I've sent a note to `unison-hackers@` about this, and we'll see if anyone is willing to put in the effort required to improve the situation.

**Comment by grothesque** [comment]
I would like to provide some more context on the mailing list, but am unable to subscribe to it.  My requests (I tried twice) are either still pending or were silently dropped.

**Comment by gdt** [comment]
Configuration for both lists have been changed which should make joining less troublesome.   I just checked the unison-hackers@ admin dashboard and it shows no pending requests.  (I personally have no access to unison-users because it's hosted by google).   The two approvers for joins to -users report approving a bunch of requests and not (intending to) decline any.   I did remember seeing a join request notice for -users in German, which was surprising 

Perhaps with the new config, joining will work?   And #711 is stil open, but likely hard.

**Comment by grothesque** [comment]
Thanks. I went to https://lists.seas.upenn.edu/mailman/listinfo/unison-hackers, entered an email address (the same as displayed on my github profile), and clicked on "subscribe".  In response, I was shown a page that said that my request will be acted upon.  I did this some days ago (two times).  I repeated the request just now.

**Comment by grothesque** [comment]
The problem was indeed on my side, I fixed it.  Thank you again for your prompt reaction and please excuse the confusion.

**Comment by gdt** [comment]
Glad it's all fixed.   The lists have had their share of issues, but I guess occasionally they are ok!
