### ISSUE TITLE
Be more specific on “Lost connection with server”

### ISSUE THREAD

**Issue by mvglasow** [bcpierce00/unison#796]
As of Unison 2.48.4, when synchronizing over SSH, there is the ominous message “Lost connection with the server”, which can be caused either by actual loss of network connectivity or by the remote end terminating the connection.

Whenever this message occurs, it is really hard to debug. In my case, the connection was ”lost” because the remote end looked for a dir named `~/.unison` and found a broken symlink at that path, and thus terminated the connection.

Suggestions for improving this:

* A connection shall be considered *lost* if, and only if, the TCP connection times out, or maybe we get some ICMP message that the remote end is no longer reachable. Anything else is a different error.
* If the connection to the server was not even established (i.e. we never completed a TCP handshake), the error message should read something line “Server is unreachable” (not sure what message 2.48.4 throws in that case, just to be sure we’re not forgetting this).
* If we get a TCP RST from the remote end, the error message should read something like “The server closed the connection”. It was not just ”lost” – the server had some reason for disconnecting us.
* If there were some error messages from the remote end along with the RST, make sure it is also displayed in the GUI.

Also, right now it is hard to tell if an error message is from the local system or the remote end. This could also be improved – at the easiest, prefix all remote error messages with “remote:” or the like.

**Comment by tleedjarv** [comment]
> As of Unison 2.48.4,

This is really old. Please upgrade to latest version (currently 2.52.1, soon to be 2.53.0) where many bugs have been fixed (but not the case with this specific issue).

> Suggestions for improving this:

I agree that theoretically there could be some improvement but your suggestions are not directly applicable here or even realistic. Only volunteers are working on issues and requests right now. Put bluntly, I think this request, unless improved, is going to be closed for a couple of reasons. The issue is unlikely to be of relevance to many users. To increase the likelyhood of someone working on this request, please phrase those suggestions in terms of POSIX syscall and libc API results and error codes, not in terms of TCP/IP stack. Ideally, provide some widely-accepted prior art (for example, is it correct that TCP RST can be simply interpreted as "Server closed connection"?).

It seems to me that the easiest way to implement this request is to just display whatever error the OS produces and not try to make it "human readable". I won't judge if this is an improvement or not.

> * If the connection to the server was not even established (i.e. we never completed a TCP handshake), the error message should read something line “Server is unreachable” (not sure what message 2.48.4 throws in that case, just to be sure we’re not forgetting this).

(Most) errors from name lookup and establishing the connection are displayed to the user as worded by the OS.

> Also, right now it is hard to tell if an error message is from the local system or the remote end. This could also be improved – at the easiest, prefix all remote error messages with “remote:” or the like.

Error messages from remote end are (and have always been) prefixed with "Server: ". If you have found specific cases where this is not true then please open a separate issue.

**Comment by gdt** [comment]
Besides 2.48 being no longer relevant, I don't follow how you expect unison to look inside ssh.    It sounds like this would have to be about ssh exit status, or perhaps interpreting things on stderr.   That raises the issue of portability to different ssh implementations (which could just be many generations of OpenSSH at this point) as unison is probably not specified to a particular one and certainly not tightly bound to a version.

**Comment by mvglasow** [comment]
Being a maintainer of some FOSS tools myself (@gdt knows what I am talking about), I do understand the other side.

Regarding the version, I am synchronizing between two machines on different hardware platforms (arm vs. x86-64) and different OS distributions (Debian vs. Ubuntu). Thus, unless I build the tool myself on two different platforms (lots of overhead for me), or the project offers .deb packages for both platforms (probably lots of overhead for you), I am limited to what the repositories of the distribution offer.

Unfortunately, since Unison (despite being a great tool for my use case – in fact the only one) is written in a rather exotic programming language, this increases the overhead of spinning up a build environment and also limits my ability to contribute code.

Just in case my report was ambiguous about that: the connection between the two systems uses SSH (I understand Unison also supports raw TCP connections, but I have never used that).

That means we are talking about the API Unison uses to establish the SSH connection. When the connection ends, does the API provide any detail (exit/return value)? If so, that might be the way to go – take the exit status and translate it into a meaningful error message. If not, then I agree there is no easy way to get clearer error messages – interpreting stderr output is a never-ending story with a lot of black magic that I wouldn’t recommend trying, so WONTFIX would be justified for that part.

What should be doable: right now, the GUI just reports that the connection was closed, while in text mode I get more detailed output (including server messages, which might provide a hint at what went wrong). Is there a way to make these accessible from the GUI (e.g. as a drop-down detail window, similar UX as when showing items that failed to sync)?

As for server-side error messages not being identified as such, I have encountered this and will open a separate issue.

**Comment by tleedjarv** [comment]
<details><summary>Offtopic...</summary>
<p>

> Regarding the version, I am synchronizing between two machines on different hardware platforms (arm vs. x86-64) and different OS distributions (Debian vs. Ubuntu). Thus, unless I build the tool myself on two different platforms (lots of overhead for me), or the project offers .deb packages for both platforms (probably lots of overhead for you), I am limited to what the repositories of the distribution offer.

Both Debian and Ubuntu provide arm binaries with glibc as the only dependency (text UI, of course). I do understand that this is in fact _the_ dependency that breaks deployments such as yours.

> Unfortunately, since Unison (despite being a great tool for my use case – in fact the only one) is written in a rather exotic programming language, this increases the overhead of spinning up a build environment and also limits my ability to contribute code.

Building Unison from source is actually very-very easy. For years I thought that setting up the build environment and building from source is too much hassle and didn't even try it. Until I discovered that you really only need GNU make, awk, sed and a standard C compiler (in other words, something that every build environment has). Then building OCaml compiler (if your platform doesn't have it packaged) is as easy as `./configure && make && make install` and after that building Unison is just `make`. (If you need the GTK GUI then that's a bit more complicated.)

</p>
</details>

Back on topic...

> That means we are talking about the API Unison uses to establish the SSH connection. When the connection ends, does the API provide any detail (exit/return value)? If so, that might be the way to go – take the exit status and translate it into a meaningful error message. If not, then I agree there is no easy way to get clearer error messages – interpreting stderr output is a never-ending story with a lot of black magic that I wouldn’t recommend trying, so WONTFIX would be justified for that part.

That's probably not possible. Unison allows using any remote shell program (not just any ssh client implementation, also non-ssh). OpenSSH man page states:
```
EXIT STATUS
     ssh exits with the exit status of the remote command or with 255 if an error occurred.
```
Even if this was considered _the_ API for the remote shell program, there is no way of knowing what the "remote command" is. It could be a wrapper around the `unison` binary, for example. I think that, for these two reasons, interpreting exit status is out of the question.

> What should be doable: right now, the GUI just reports that the connection was closed, while in text mode I get more detailed output (including server messages, which might provide a hint at what went wrong). Is there a way to make these accessible from the GUI (e.g. as a drop-down detail window, similar UX as when showing items that failed to sync)?

I'm happy to report that this is already partially implemented since 2.52.0 (https://github.com/bcpierce00/unison/pull/632).

Going further than that is somewhat doable but really tricky. The reason why you get server messages in text mode is simply because remote stderr is redirected to local stderr by `ssh`. So it looks like the errors/messages are printed locally but they are not, it's just that local stdout, local stderr and remote stderr are all mixed together.

Displaying remote stderr in GUI is doable because remote stderr is already captured separately (see the PR mentioned above). It becomes very tricky because Unison produces a lot of output on stderr, not just fatal errors. This is a long-known issue, see: https://github.com/bcpierce00/unison/blob/76e0b4eeaf3ef1d55fff1e7eb4dd27981c4b848b/src/TODO.txt#L258-L263

I'm happy to write the code when someone creates an exact specification for what should go to stdout and what to stderr. Then it may become possible to display all remote stderr output in the GUI.

**Comment by gdt** [comment]
It sounds like 2.52.1 and master are improved from 2.48, and we have declared that we don't pay attention to old versions.   So I think this is ready to close.   Please feel free, after upgrading to master, to discuss improvements on unison-hackers@, so that we get more eyes on the discussion.

**Comment by mvglasow** [comment]
All right, guess I should find a way to update my machine zoo, then :-) Happy to hear that we are getting server messages in the GUI as of 2.52.
