### ISSUE TITLE
Unison fails to find proper lablgtk path under an OPAM environment

### ISSUE THREAD

**Issue by ejgallego** [bcpierce00/unison#9]
Under an OPAM system, Unison fails to find the proper lablgtk2 path, as this recipe:

```
OCAMLLIBDIR=$(shell ocamlc -v | tail -1 | sed -e 's/.* //g' | tr '\\' '/' | tr -d '\r')
```

doesn't quite work under OPAM as it uses a different library layout.

My preferred solution to locate Ocaml dependencies using `ocamlfind`, however that would add a new dependency to Unison's build.

If you'd be willing to accept that new dependency I'd be happy to provide a patch, another solution would be to detect if `ocamlfind` is installed and use it, however, my Make-foo is not so good to implement that reliable.

**Comment by ejgallego** [comment]
IMO using `ocamlfind/ocamlbuild` would provide significant benefits to the build process in both OSX and Linux (I really have no clue about how it works for Windows, maybe @gashe can comment?)

**Comment by bcpierce00** [comment]
I am indeed a bit reluctant to add a new dependency — Unison gets built by all sorts of people on all sorts of platforms.  But would it be hard to have the makefile check for the presence of ocamlfind and use it iff it’s available?

    - B

**Comment by ejgallego** [comment]
Hi Benjamin, I agree this is the best approach, even if ocamlfind is likely to be included with future ocaml versions.

I've made a (preliminary) pull-request adding ocambuild support that can be used if wanted.

**Comment by ejgallego** [comment]
Ok, #10 allows to build unison in Linux using OPAM/Ocambuild. Unfortunately I can't test the patch on OSX or Windows.

**Comment by gasche** [comment]
I think there are two orthogonal things at play here:
- `ocamlfind` is a tool to reliably find OCaml libraries installed on the system, and I think this is what is needed to solve the current issue
- `ocamlbuild` is a build system that can replace Make in deciding how to build OCaml projects; it also makes it simple to use ocamlfind libraries, which I suppose is why Emilio implemented ocamlfind support by switching to ocamlbuild as the build system

I think that it would be clearer to try to keep the existing Make system in place, and just call `ocamlfind ocamlc` instead of `ocamlc` in the build steps (when ocamlfind is available, etc.). This would result in a less invasive change that would be easier to understand for maintainers and clearly preserve behaviour for non-ocamlfind users. If there is interest in using ocamlbuild as the underlying build system for the project, that could also be an interesting development, but I think that it should be considered separately.

@ejgallego , would you be interested in trying to just use ocamlfind without ocamlbuild, and compare the resulting patch? I know that means redundant work compared to what you have already done, but I think that could be helpful. To do this, I would try changing `Makefile.OCaml` only; the cleanest approach if this was done from scratch would be to use `ocamlfind ocamlc -package lablgtk(2)` and `ocamlfind ocamlopt -package lablgtk(2)` instead of the current combination of `ocaml{c,opt}` and `-I +lablgtk(2)` flags, but one thing that may be easier to do given the current code is to instead call `ocamlfind query -i-format lablgtk(2)` (you can also use `ocamlfind query -a-format -predicates {byte,native} labglgtk(2)` to get the archive names, but I except the current ones to keep working indefinitely).

**Comment by ejgallego** [comment]
Hi @gasche , thanks a lot for you help!

I thought of that, but IMHO Benjamin is right about maybe keeping the legacy system unchanged, and given that the Unison makefile doesn't look too different from the standard Ocaml makefile I thought that providing the straightforward ocambuild option would be good and lightweight.

**Comment by ejgallego** [comment]
@gasche also, I didn't do what you suggest not because I do think it is a bad solution, but because my Make-foo is frankly quite sub-standard. Of course, we should pick whatever solution Benjamin thinks fit better with Unison, I'd happy to try that if he wants.

**Comment by bcpierce00** [comment]
I agree with Gabriel that the best way is to just use ocamlfind (if it exists) from the existing Makefile.Ocaml.   

With make there’s always a danger of making things too complicated by trying to do too much or do it too automagically, so your lack of make-fu is actually a benefit!  :-)  

Let’s look for the minimal change that will let Unison build in opam environments.

   - B

**Comment by ejgallego** [comment]
#95 should close this issue.

I'd be great if @bcpierce00 would reconsider #10 , that non-invasive patch provides significant advantages to setup an OCaml dev enviroment for Unison.

**Comment by bcpierce00** [comment]
Does #95 still need to be included?  (I'm a relative github novice, and I'm not sure I'm correctly understanding what it's telling me...)

**Comment by ejgallego** [comment]
@bcpierce00 all is fine AFAICS, thanks!
