### ISSUE TITLE
Where is the manual?

### ISSUE THREAD

**Issue by metov** [bcpierce00/unison#924]
There is a manual at https://www.cis.upenn.edu/~bcpierce/unison/download/releases/stable/unison-manual.html but it's for v2.48.4 (seems like v2.52 is current) and it's dated 2012. Also the site itself says it is out of date.

The readme focuses mostly on installing/building and doesn't go into details about using the program. It also doesn't link to any manuals. The same is true for the wiki

In the repository I see `doc/` directory, but it's a mystery to me where these get compiled to.

Where is the up-to-date manual for Unison?

**Comment by gdt** [comment]
The README loudly points to https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests which asks that issues only be filed for bugs, and not support requests.  Please address questions to the unison-users mailinglist.

**Comment by gdt** [comment]
See #819, and (newly updated) https://github.com/bcpierce00/unison/wiki/Downloading-Unison and https://github.com/bcpierce00/unison/wiki/CI-Binary-instructions

**Comment by metov** [comment]
I actually meant this as a bug report. Clearly a lot of work has gone into writing resources like the older manual I linked to. I assumed someone just forgot to add the link to the readme and thought I would let you know. Sounds like this is not the kind of feedback you're looking for, sorry about that.

**Comment by gdt** [comment]
Questions like you asked are welcome on the mailnglists, as https://github.com/bcpierce00/unison/wiki/Reporting-Bugs-and-Feature-Requests tries to say.   As a matter of doctrine, unison's product is the source code, and we beileve the manual is buildable following the instructions.   As for it being a bug, it's a dup of #819; I just adjusted the title to make it more findable, but the number of open bugs is now small enough to skim -- when I started it was vastly higher.   

As the comments say above, your question did provoke some documentation changes, plus the withdrawal of the old manual.   (The request for people to provide CI binary instructions has been outstanding for a really long time, with no responses.)  Sorry, but we suffer from github culture disease (where issue trackers are for all interaction because they don't provide mailinglists) and it's a tremendous amount of work to keep the tracker limited to actual bugs.   Hence the request to use the mailinglist for questions -- if there were 200 issues instead of 70, it would be infeasible for humans to scan them.

**Comment by metov** [comment]
In hindsight, I think I was hoping someone would add a note to the readme saying the manual isn't hosted anywhere, and you need to run `make` inside `doc/` to generate it, or something like that. Well, at least I was able to figure it out...

Check out https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions if it's such a big problem

**Comment by gdt** [comment]
We use the mailinglist, as the document I linked above says.  unison is not a github project, but a project that existed before, and which is considering departing github, for the usual set of reasons.  Tighter integration would be a bug not a feature.

**Comment by sgtcoder** [comment]
I agree, where is the documentation? Are we supposed to dig through the source code?

**Comment by sahil-sagwekar2652** [comment]
How about hosting the [unison-manual.html](https://raw.githubusercontent.com/bcpierce00/unison/documentation/unison-manual.html) on this repository's GitHub pages?

**Comment by metov** [comment]
@sgtcoder Check out my other comment. You can build the docs yourself using the makefile.

@sahil-sagwekar2652 It would be nice, but since they are thinking of leaving Github, that would presumably have the problem of making migration more difficult.
