### ISSUE TITLE
README.md does not point out that the manual is available on github

### ISSUE THREAD

**Issue by bcpierce00** [bcpierce00/unison#948]
Someone just emailed me to let me know that the user manual, which they had hoped to find via the old Unison Wiki, was offline.  I was about to tell them to look here, but then double-checked and discovered that it doesn't seem to be anywhere at all...  

Would it be hard to build an HTML or text manual and make it available either at the top level (linked from the README, obviously only for the current version) or as part of the release products?

**Comment by gdt** [comment]
It is available from the top-level wiki page:
  https://github.com/bcpierce00/unison/wiki

And, it's in most (all) release artifacts; I just downloaded https://github.com/bcpierce00/unison/releases/download/v2.53.3/unison-2.53.3+ocaml4.08-ubuntu-x86_64.tar.gz because it's first, and it's there.

If you want to copy the wiki pointer into README without overemphasizing it as the readme is now trying to be terse, and also make the key point that the issue tracker is not for question, that's fine with me.

**Comment by gdt** [comment]
Actually I just did.

Now we'll just get complaints that it isn't first :-(

**Comment by bcpierce00** [comment]
Thanks.  I also did a little editing of the Wiki to make the documentation link more prominent.
