### ISSUE TITLE
Document how to download and build OCaml compiler

### ISSUE THREAD

**Issue by pamolloy** [bcpierce00/unison#963]
`INSTALL.md` mentions downloading and building the OCaml compiler (see [INSTALL.md:75](https://github.com/bcpierce00/unison/blob/master/INSTALL.md?plain=1#L75)). Perhaps it is worth adding a link to where the souce can be downloaded? I could only find official documentation for installing the pre-built compilers.

**Comment by pamolloy** [comment]
Does https://github.com/ocaml/setup-ocaml do this? I looked around a bit, but I'm not familiar with Github Action implementations.

**Comment by pamolloy** [comment]
Perhaps a link to https://github.com/ocaml/ocaml/blob/trunk/INSTALL.adoc?

**Comment by pamolloy** [comment]
And suggest the version specified here: https://github.com/bcpierce00/unison/blob/master/.github/workflows/CI.yml#L25C25-L25C31

**Comment by tleedjarv** [comment]
`setup-ocaml` is useful _only_ for Github Actions, it is not useful in any other environment.

I'd be cautious adding this information in INSTALL.md as it's already quite long and this is very specific information not needed by vast majority of users. This could be a great addition in the wiki. Unfortunately, wiki was closed for public editing due to spam.

**Comment by pamolloy** [comment]
Yah, the OCaml ecosystem is extraordinarily confusing and `INSTALL.md` seems to make it more confusing. In one section is suggests building the OCaml compiler from source and in the next that Unison can be cross compiled. What appears to be missing is a link to the pre-built OCaml compiler that can cross compile it, which apparently are prefixed like GCC?

Googling leads to a bunch of third-party projects supporting cross compilation since OCaml itself doesn't support it?

The documentation for the OCaml compiler mentions building for a different architecture (see [INSTALL.adoc?plain=1#L72](https://github.com/ocaml/ocaml/blob/trunk/INSTALL.adoc?plain=1#L72)). The description and the code sample appear to be reversed. However, I assume that is just cross-compiling the compiler and not adding cross-compiler support to the compiler. Either way I couldn't get either to work.

**Comment by tleedjarv** [comment]
> Yah, the OCaml ecosystem is extraordinarily confusing

That's true.

> and `INSTALL.md` seems to make it more confusing.

Not sure why you get that feeling. Improvements would be very welcome if we can identify what exactly is causing confusion. See below.

> In one section is suggests building the OCaml compiler from source and in the next that Unison can be cross compiled. What appears to be missing is a link to the pre-built OCaml compiler that can cross compile it, which apparently are prefixed like GCC?

Could you describe a little more about what you are trying to achieve in the first place? The `INSTALL.md` sections are not meant to be executed sequentially, they are various alternatives available to various needs. Is this something that should be clarified there?

While you are fully correct in saying `the OCaml ecosystem is extraordinarily confusing`, the basic promise of `INSTALL.md` is that you don't _need_ any of that complexity just to compile Unison from source. You don't need any of the developer tools, you don't need to set up an IDE for yourself. The same logic applies to pretty much any language. Is this something that should be stressed there?

You just need the OCaml compiler itself. (You don't even need the native code compiler, byte code suffices.)
You _don't need_ dune.
You _don't need_ opam.
You _don't need_ ocamlfind.
You _don't need_ LSP or ppx or anything else you might see mentioned in various instructions.
You don't need anything else other than the pre-reqs listed in `INSTALL.md`.
(my own env doesn't have any of the above, for example)

_Ideally,_ you install the pre-reqs via your chosen package repository and you're done. This doesn't have to be your platform's native package management system, it could be something like pkgsrc, for example.

I do get that OCaml installation guides can make it more complicated than it should be but OCaml installation instructions do not belong within Unison's installation instructions. It would be like adding gcc and glibc build instructions to a project written in C.

**Comment by gdt** [comment]
If anything, I think we should prune instructions about how to build ocaml.    Packages do not tell people how to build gcc, or cmake, or numpy.   We should be able to refer to the prerequisite software in a packaging/distribution-neutral manner.

**Comment by pamolloy** [comment]
I would really appreciate help with the following questions:

- Where can I find pre-built cross OCaml toolchains (i.e. that would be used with `TOOLPREFIX`)?
- Is it possible to build or configure `ocamlopt` to build for a different architecture than it was compiled for?

**Comment by gdt** [comment]
Requests for help are out of order in issues.  Please as on unison-users@.

**Comment by pamolloy** [comment]
The project Makefile defines a variable and the project Documentation explains to pass it a path to a file. And I'm asking how to use that project specific feature.

I'm not an active member by any means, but have at least tested the new xattrs functionality when I had the opportunity. And I would have been be happy to improve the documentation.

**Comment by gdt** [comment]
Please join the mailinglist and feel free to discuss there.   I am not trying to tell you to go away.   Issues are essentially only seen by two of us, and do not help build community.   There is a culture within github of using issues for everything, and the project has said and documented that we aren't doing that. That's why the wiki page explaining about reporting bugs says to use the mailnglists for things that are not clearly articulated bugs in the source code. 

What's going on here, in my view, is that people see that the unison project should be helping people with ocaml, because unison is written in ocaml, and I disagree with that at a fundamental level.

A PR to list a page from the ocaml world that is sort of "entry point for how to get ocaml on your machine" next to the "you need ocaml" prereq statement would be great.

See #966 to detangle instructions for building ocaml from unison.   I think this is the real bug surfaced by this issue.
