### ISSUE TITLE
Add ability to run as a daemon and synchronize changes as they happen if possiible

### ISSUE THREAD

**Issue by anadon** [bcpierce00/unison#976]
Using raw inotify or Watchman (https://github.com/facebook/watchman), run as a daemon and synchronize machines provided there is a connection.  

There are considerations on handling conflicting changes or infinite propagating changes when there are more than two systems, but I think those could be handled by just not supporting that many machines explicitly and deferring to manual intervention for conflicts for now.  When there is not an internet connection, it should be easy to have a log of files to synchronize when a connection does become available again.  My primary usage is editing documents between by desktop and laptop, and I don;t use both at the same time.

**Comment by gdt** [comment]
Please bring this up on unison-hackers.   Somewhat this is supported, and for the most part there are complicated issues that make this not a clearly-implementable feature request.

DId you find the Reporting Bugs wiki page and read it?  I ask because we've had a lot of issues opened that don't fit our guidelines, and I'm trying to understand if the guidelines are unclear, or if people aren't reading the wiki page.

**Comment by anadon** [comment]
I did read it, and looked through what I could find for similar requests.  I'll post there.

**Comment by gdt** [comment]
Thanks.   It's a big discussion, and one of the bugs of github is that only the maintainers are subscribed-all here, I think, vs about 400 on hackers.  See you on the list.
