### ISSUE TITLE
Feature Request - Have option to move deleted files to a trash bin or some specified folder.

### ISSUE THREAD

**Issue by domdog** [bcpierce00/unison#995]
I make mistakes and having mistakenly deleted files is horrible.  I would like the option to have deleted files directed to a folder as an option.  I could then keep them for a while just in case then flush them when I am assured the sync went as planned.

**Comment by avollmerhaus** [comment]
Apart from Unison adding this feature, maybe a viable solution for you would be to use a filesystem with snapshots. BTRFS or ZFS (and probably others) allow for regular snapshots for the filesystem state to be taken, so in case you accidentally delete something you can get it back from the latest snapshot.

**Comment by tleedjarv** [comment]
You should ask this question in the mailing list. I'm sure others have suggestions you could try.

I don't know how well it would work because I don't use the backups feature myself, but Unison does have built-in backup functionality. Have a look at the "backup" preference and the related ones, like "backuploc". This feature would backup _all_ changes, however, not just deletions.

**Comment by gdt** [comment]
This does belong on the list; the tracker (wrt features) is  for reasonably baked feature requests that address the complexities of what the feature would do and why.   It might also result in comments for other users about how they address this.   This is especially true given the existing backup preference, which seems to do what I think you want.
